SkillsFundingAgency/dfc-coursedirectory

Resources/AzureSearch/SearchIndexer.json
Wrong mapping function used in the Azure search indexer
=> NCSD-742: Azure search indexer fix

src/Dfc.CourseDirectory.WebV2/Filters/CurrentProviderResourceFilter.cs, src/Dfc.CourseDirectory.WebV2/Filters/RedirectToProviderSelectionActionFilter.cs, src/Dfc.CourseDirectory.WebV2/ModelBinding/CurrentProviderModelBinder.cs, src/Dfc.CourseDirectory.WebV2/RedirectToActionResultExtensions.cs, src/Dfc.CourseDirectory.WebV2/Security/ClaimsPrincipalCurrentUserProvider.cs, src/Dfc.CourseDirectory.WebV2/ServiceCollectionExtensions.cs, src/Dfc.CourseDirectory.WebV2/TagHelpers/CurrentProviderFormTagHelper.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FilterTests/CurrentProviderResourceFilterTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FilterTests/RedirectToProviderSelectionActionFilterTests.cs
Previously it was done in a model binder so wasn't always available.
=> Move active provider resolution into a resource filter

src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/EnsureApprenticeshipQAStatusSetForProviderHandler.cs
A previous sign in action creates the provider record with a null QA
status. Fix the merge statement to handle a null value as well as
missing row.
=> Fix upserting QA status

src/Dfc.CourseDirectory.WebV2/Helpers/UkrlpSyncHelper.cs, tests/Dfc.CourseDirectory.WebV2.Tests/Helpers/UkrlpSyncHelperTests.cs
Changed the default ProviderType = Both when creating new provider via UKRLP sync
=> PTCD-138 Changed the default ProviderType = Both when creating new provider via UKRLP sync + unit tests changes

tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/NewApprenticeshipProvider/QANotificationsTests.cs
- Remove passed notification check as the passed banner is no visible for providers that have either closed the notification or if the provider has been migrated as passed (without a submission).
=> remove passed notificationcheck as this is covered by other tests.

src/Dfc.CourseDirectory.Web/Views/Apprenticeships/Details/Index.cshtml
ptcd-306 #updated email regex validation to follow https://en.wikipedia.org/wiki/Email_address#RFC_specification a little bit better.
**Valid Email formats tested.**
a-persons-name@se.training
kevin_joy@fdf.uk.com
KEVIN_JOY@esynery-solutions.co.uk
KEVIN$@esyn.uk.com
2@t.com
$@sd.com
.@domain.com
!#$%&'*+-/=?^_`{|}~@madeupdomain.com
kevin'joy@esyn.co.uk
kevin@kevin.com
kevin@domain.me
kevin@domain.ltd
kevin@domain.org
kevin@domain.co
kevin@gov.uk
kevin@test.io
kevin@domain.london
kevin'joy@domain.xyz
kevin@media.media
kevin-joy@domain.com
**Rejected Email Formats** 
kevin@m.m
:@ds.com
kevin.joy@.com
@fd.com
tesT@192.168.0.1
=> ptcd-306 #amended email regex to handle different domains.

src/Dfc.CourseDirectory.Functions/CommitSqlTransactionFunctionInvocationFilter.cs, src/Dfc.CourseDirectory.Functions/FunctionInstanceServicesCatalog.cs, src/Dfc.CourseDirectory.Functions/Startup.cs
Azure Functions' `IFunctionInvocationFilter` doesn't currently expose the `IServiceProvider` used for the instance. This adds an `IJobActivatorEx` decorator that captures the services so they can be looked up later.
=> Commit SQL transction at the end of function execution

src/Dfc.CourseDirectory.Web/Views/UnRegulatedCourses/UnknownZCode.cshtml
Removing click event from ellipsis 
page should not be refreshed if user click on ellipsis
=> Fix removing click event from ellipsis in pager (PTCD 22)

src/Dfc.CourseDirectory.Services/ApprenticeshipSettings.cs, src/Dfc.CourseDirectory.Services/Interfaces/IApprenticeshipSettings.cs, src/Dfc.CourseDirectory.Web/Controllers/ApprenticeshipsController.cs, src/Dfc.CourseDirectory.Web/appsettings.json, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/NewApprenticeshipProvider/FlowModelInitializerTests.cs
Some observations:
- Radius appsetting is a string, `IOptions<ApprenticeshipSettings>` casts to int, controller subsequently performs a ToString() on the value 🤦 
- SubRegionRadius does not appear to be used right now. Adjusted to match new minimum default radius.
- Config should be moved over to an Azure DevOps configuration using parameters.json substitution.
=> PTCD-346 - increase default radius to 30

tests/Dfc.CourseDirectory.Testing/DatabaseFixture.cs
By setting the 'CD_SkipTestSqlDeployment' environment variable to true
the database schema will not be updated.
This should help running tests on non-Windows environments.
=> Allow skipping SQL database deployment for tests

src/Dfc.CourseDirectory.Web/Properties/launchSettings.json
Launching from `dotnet run` caused a port conflict because it was set to
launch https and http on the same port.
=> Make dev launch ports consistent

src/Dfc.CourseDirectory.Web/Controllers/HomeController.cs
The "continue to course directory" link on the migration report ( https://localhost:44345/Migration/Report ) was
redirected back to itself via HomeController/index.
Cathie> The link states the user should go back to the Course Directory
homepage.  Once the user has returned to this page, they can return to
the Migration report via the link in the blue box to resolve the issues
of those courses pending.  The user should be able to add more courses
as required - it could be that they don’t have the required information
to resolve those courses that require fixing, but this should not stop
them from adding/amending other course information. As long as they can
return to the Migration report having logged in/out to resolve these
issues, then it will be fine.
There is no test coverage at the …
=> PTCD-305 Remove redirect for pending migrations

src/Dfc.CourseDirectory.Web/Controllers/AddCourseController.cs, src/Dfc.CourseDirectory.Web/ViewComponents/CourseName/CourseNameModel.cs, src/Dfc.CourseDirectory.Web/ViewComponents/CourseName/Default.cshtml, src/Dfc.CourseDirectory.Web/Views/AddCourse/AddCourseRun.cshtml, src/Dfc.CourseDirectory.Web/Views/CopyCourseRun/CopyCourseRun.cshtml, src/Dfc.CourseDirectory.Web/Views/EditCourseRun/EditCourseRun.cshtml, src/Dfc.CourseDirectory.Web/Views/Shared/_Layout_Your_Courses.cshtml
As per prototype and change document.
Diff best viewed with whitespace changes off due to re-indentation and whitespace stripping.
The backlink has been moved out of `<main>` because it's more semantically correct (I think) and that's how it is on the Design System example: https://design-system.service.gov.uk/patterns/question-pages/default/index.html
See individual commit messages for detailed changes
=> PTCD-410 - Updated copy and design for course details page

src/Dfc.CourseDirectory.Web/Views/AddCourse/AddCourseRun.cshtml
As per prototype, after discussing with Cathie
Titles changed:
* Course hours
* Attendance pattern
This now matches the summary page
=> PTCD-410 Updated labels on course details

src/Dfc.CourseDirectory.Functions/host.json
Dependency tracking is filling up logs with (expensive) noise and we're losing important logs.
=> Disable AI dependency tracking for Functions app

src/Dfc.CourseDirectory.Web/Controllers/LarsSearchController.cs, src/Dfc.CourseDirectory.Web/ViewComponents/LarsSearch/Default.cshtml, src/Dfc.CourseDirectory.Web/ViewComponents/LarsSearchResult/Default.cshtml, src/Dfc.CourseDirectory.Web/ViewComponents/LarsSearchResult/LarsSearchResultModel.cs
Note there are a tonne of problems with this page:
- searches are all done client-side with JavaScript;
- paging links don't do the expected thing;
- window not scrolled to top after changing criteria;
- no loading state;
- no error state
- etc...
but this PR doesn't attempt to fix any of them.
=> Add paging to LARS search results (PTCD-22)

src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/UpsertProvider.cs, src/Dfc.CourseDirectory.Core/SqlDataSync.cs
Some Cosmos data has default(DateTime) for the DateUpdated field -
that's not a valid value for a SQL DateTime. Replace those values with
nulls.
=> Handle default(DateTime) when syncing provider records

tests/Dfc.CourseDirectory.Testing/DatabaseFixture.cs, tests/Dfc.CourseDirectory.Testing/DatabaseTestBase.cs
Having multiple builds hitting the CI DB at the same time leads to
errors. Introduce a lock that will limit the concurrency to one.
=> Fix integration tests for concurrent CI builds

tests/Dfc.CourseDirectory.Testing/DatabaseFixture.cs
Both schema deploys and test execution should be protected from
concurrent test runs.
=> Acquire the lock before deploying database schema

tests/Dfc.CourseDirectory.Web.Tests/Controllers/BulkUploadApprenticeshipsControllerTests.cs, tests/Dfc.CourseDirectory.Web.Tests/Controllers/FakeSession.cs
We want to refactor this action so need test coverage to prevent regressions.
This gives us 100% coverage on the controller action for posting an apprenticeship bulk upload file; with the service mocked out.
=> PTCD-508 - Add test coverage for upload action of BulkUploadApprenticeshipsController

Dfc.CourseDirectory.Services.Tests/BulkUploadService/Apprenticeship/ApprenticeshipBulkUploadServiceTests.cs, Dfc.CourseDirectory.Services.Tests/BulkUploadService/Apprenticeship/ApprenticeshipCsvBuilder.cs, Dfc.CourseDirectory.Services.Tests/BulkUploadService/Apprenticeship/ApprenticeshipCsvRowBuilder.cs, Dfc.CourseDirectory.Services.Tests/BulkUploadService/Apprenticeship/ApprenticeshipCsvStructure.cs, Dfc.CourseDirectory.Services.Tests/Dfc.CourseDirectory.Services.Tests.csproj, Dfc.CourseDirectory.sln, src/Dfc.CourseDirectory.Models/Models/Auth/AuthUserDetails.cs, src/Dfc.CourseDirectory.Models/Models/Venues/Venue.cs
These are "characterization tests" to show the current behaviour of the
system without introducing modifications, with a view to being able to
confidently change and refactor the code later.
* Add parameterless constructor to data objects to simplify testing.
* Make venue name settable so we can use an object initializer.
Written by Tim, with some pairing from James & James.
This is not complete coverage, there is plenty more to do (some todos in the PR), but it's a good start, and I think worth getting in as-is as a base for extending as desired.
Areas that need more work:
* testing exactly what is passed on to the next link in the chain
* what does the background upload process do, does it share the code?
* testing of any transformations made on the way through
=> PTCD-508 - Add test coverage for apprenticeship bulk upload service

tests/Dfc.CourseDirectory.WebV2.Tests/CourseDirectoryApplicationFactory.cs
This should actually fix the flaky CI runs
=> Release the integration test DB lock for MVC-based tests

src/Dfc.CourseDirectory.Web/Controllers/BulkUploadApprenticeshipsController.cs, tests/Dfc.CourseDirectory.Web.Tests/Controllers/BulkUploadApprenticeshipsControllerTests.cs
* Whitespace code cleanup.
* Reduce nesting by using early-return.
* Dispose of stream correctly, adjust test to verify stream during call to mock instead of verify where it is already disposed.
This patch reduces the "cognitive complexity" of the Index action from 31 to 10 as measured by https://plugins.jetbrains.com/plugin/12024-cognitivecomplexity/
There's more we could do on this but we're moving on to other tasks for now.
=> [PTCD-528] Refactor apprenticeship bulk upload controller

src/Dfc.CourseDirectory.Services/BulkUploadService/ApprenticeshipBulkUploadService.cs, tests/Dfc.CourseDirectory.Services.Tests/BulkUploadService/Apprenticeship/LocationVariationFacts.cs
Set delivery_mode to employer if delivery_method is employer. This is the change in behaviour requested in the jira ticket:
> "Current apprenticeship bulk upload implementation will always have delivery modes empty for a location that is employer based. This is different behaviour to the non-bulk upload journey, which sets the delivery modes to Employer. Change required to make bulk upload on apprenticeships to include 'employer' as the delivery mode."
This follows the existing pattern of mutating data in the `Mandatory_Checks_*` methods.
This is the minimum patch needed to achieve the requested behaviour change in order to separate it from refactorings to improve the code.
https://skillsfundingagency.atlassian.net/browse/PTCD-508
=> [PTCD-508] Set delivery_mode to employer in bulk upload

src/Dfc.CourseDirectory.Web/Views/Apprenticeships/Details/Index.cshtml, src/Dfc.CourseDirectory.Web/Views/EditApprenticeship/EditApprenticeship.cshtml, src/Dfc.CourseDirectory.WebV2/Features/NewApprenticeshipProvider/ApprenticeshipDetails.cshtml
Updated apprenticeships guidance link for Apprenticeship details, edit apprenticeship and new apprenticeship provider
Change from https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/746087/course_directory_provider_portal_user_guide_v7.pdf to https://www.gov.uk/government/publications/find-apprenticeship-training-how-to-submit-data
=> PTCD-506 Fix Apprenticeships Guidance Link

src/Dfc.CourseDirectory.Web/ViewComponents/BackgroundBulkUploadNotification/Default.cshtml
* The code was not in use so can safely be removed.
* The removed call to `FindSystemTimeZoneById()` fails on linux due to a different timezone list. See https://dejanstojanovic.net/aspnet/2018/july/differences-in-time-zones-in-net-core-on-windows-and-linux-host-os/
* Added missing spaces after full stops in message.
Tripped over this while troubleshooting an unrelated bulk upload issue.
=> PTCD-528 Remove windows-specific dead code from "bulk upload processing" notice

src/Dfc.CourseDirectory.Web/Views/CopyCourseRun/CopyCourseRun.cshtml
Fix CopyCourseRun Qualification Details notification - Qualification name bug
The "Qualification name" field was referencing the incorrect model value.
=> PTCD-424 Fix CopyCourseRun Qualification Details Bug

src/Dfc.CourseDirectory.Web/Controllers/ProviderSearchController.cs, src/Dfc.CourseDirectory.Web/RestrictApprenticeshipQAStatusAttribute.cs, src/Dfc.CourseDirectory.Web/ViewComponents/Dashboard/Dashboard.cs, src/Dfc.CourseDirectory.Web/Views/Shared/_GovukHeaderPartial_Your_Courses.cshtml, src/Dfc.CourseDirectory.WebV2/Behaviors/RequireUserCanAccessCourseBehavior.cs, src/Dfc.CourseDirectory.WebV2/Features/IRequiresProviderContextController.cs, src/Dfc.CourseDirectory.WebV2/Features/NewApprenticeshipProvider/NewApprenticeshipProviderController.cs, src/Dfc.CourseDirectory.WebV2/Features/NewApprenticeshipProvider/QANotificationsViewComponent.cs, src/Dfc.CourseDirectory.WebV2/Features/Providers/ProvidersController.cs, src/Dfc.CourseDirectory.WebV2/Filters/ProviderContextResourceFilter.cs, src/Dfc.CourseDirectory.WebV2/Filters/RedirectToProviderSelectionActionFilter.cs, src/Dfc.CourseDirectory.WebV2/Filters/VerifyApprenticeshipIdActionFilter.cs, src/Dfc.CourseDirectory.WebV2/HttpContextFeatures/ProviderContextFeature.cs, src/Dfc.CourseDirectory.WebV2/IProviderContextProvider.cs, src/Dfc.CourseDirectory.WebV2/ModelBinding/ProviderContextModelBinder.cs, src/Dfc.CourseDirectory.WebV2/ProviderContext.cs, src/Dfc.CourseDirectory.WebV2/ProviderContextProvider.cs, src/Dfc.CourseDirectory.WebV2/ProviderInfoCacheExtensions.cs, src/Dfc.CourseDirectory.WebV2/RedirectToActionResultExtensions.cs, src/Dfc.CourseDirectory.WebV2/RequiresProviderContextAttribute.cs, src/Dfc.CourseDirectory.WebV2/SharedViews/_V2LayoutProviderContext.cshtml, src/Dfc.CourseDirectory.WebV2/TagHelpers/AppendProviderContextTagHelperComponent.cs, src/Dfc.CourseDirectory.WebV2/UrlExtensions.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FilterTests/ProviderContextResourceFilterTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FilterTests/RedirectToProviderSelectionActionFilterTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FilterTests/VerifyApprenticeshipIdAttributeTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/RedirectToActionResultExtensionsTests.cs
Provider Context is conceptually the 'current provider'. The legacy views use the `UKPRN` in Session for storing this; v2 bits can use a `providerId` query parameter, a `providerId` route value or the provider ID can be extracted from whatever entity is being acted upon (e.g. a Course).
This PR removes some of the inconsistencies and ties up some lose ends around the current usage. A separate PR will follow that removes the `VerifyApprenticeshipId` attributes & filters and replaces it with something in line with what we do for courses (i.e. a MediatR behavior).
- Use IProviderContextProvider everywhere for getting/setting provider context.
- Move the session-based fallback into IProviderContextProvider
- Remove IRequiresProviderContextController (it was a convenience that brings more …
=> Rationalise Provider Context

src/Dfc.CourseDirectory.Core/ReferenceData/Lars/LarsDataImporter.cs, tests/Dfc.CourseDirectory.Core.Tests/ReferenceDataTests/LarsDataImporterTests.cs
This PR is for discussion of an additional change to #1636 that's already in QA.
---
Wondering whether to "just do this" to fix up the join table. Penny for your thoughts.
`LearningDeliveryCategory` appears to be a join table between `Category` and `LearningDelivery`.
* Filter out records that don't have matches in either of the related tables.
* Add log of number excluded
Narahari pointed out that this table is including records that have no match in related tables due to filtering.
=> Exclude unrelated LearningDeliveryCategory records

src/Dfc.CourseDirectory.WebV2/SharedViews/Components/AdminProviderContextNav.cshtml, src/Dfc.CourseDirectory.WebV2/SharedViews/Components/ProviderTopNav.cshtml, tests/Dfc.CourseDirectory.WebV2.Tests/LayoutTests.cs
Previously link was only shown for Both providers if bulk upload is enabled (copy/paste error).
=> Fix nav to show 'Your apprenticeships training' for app-only providers

src/Dfc.CourseDirectory.Core/Dfc.CourseDirectory.Core.csproj, src/Dfc.CourseDirectory.Core/Search/AzureSearch/AzureSearchClient.cs, src/Dfc.CourseDirectory.Core/Search/AzureSearch/AzureSearchQueryBuilder.cs, src/Dfc.CourseDirectory.Core/Search/AzureSearch/IAzureSearchQuery.cs, src/Dfc.CourseDirectory.Core/Search/AzureSearch/ServiceCollectionExtensions.cs, src/Dfc.CourseDirectory.Core/Search/ISearchClient.cs, src/Dfc.CourseDirectory.Core/Search/Models/Provider.cs, src/Dfc.CourseDirectory.Core/Search/ProviderSearchQuery.cs, src/Dfc.CourseDirectory.Core/Search/SearchResult.cs, tests/Dfc.CourseDirectory.Core.Tests/Search/AzureSearch/AzureSearchClientTests.cs, tests/Dfc.CourseDirectory.Core.Tests/Search/AzureSearch/AzureSearchQueryBuilderTests.cs, tests/Dfc.CourseDirectory.Core.Tests/Search/ProviderSearchQueryTests.cs
Add AzureCognitiveSearchClient with Provider search implementation to CourseDirectory.Core
For a bit of background, search functionality currently calls an external API (FAC) to query Azure CognitiveSearch - the implementations are messy and inconsistent and there's a lot of functional code spread out across multiple projects/classes that can influence the results.
The aim of this PR is to create an easily configurable search client that can be used directly by CourseDirect to talk to Azure directly.
This code is not currently being consumed, and therefore won't require testing, however the next iteration will see this implemented for both Provider search (PTCD-439) and LARS search (PTCD-470). We can migrate the rest of the search indexes across at our leisure.
=> PTCD-439 AzureCognitiveSearchClient Implementation with Provider Search

src/Dfc.CourseDirectory.WebV2/ProviderContextProvider.cs
A 'strict' provider context indicates that, once set, the provider cannot be changed for a given request.
Previously we would blow up if the set context was strict but the one being set was not. This changes the behavior so we maintain the strict-ness but don't explode.
=> Fix setting provider context more than once when a non-strict context follows a strict one

tests/Dfc.CourseDirectory.WebV2.Tests/CourseDirectoryApplicationFactory.cs, tests/Dfc.CourseDirectory.WebV2.Tests/MvcTestBase.cs, tests/Dfc.CourseDirectory.WebV2.Tests/SingletonSession.cs, tests/Dfc.CourseDirectory.WebV2.Tests/Startup.cs
Use a single dictionary to back all sessions. This allows us to
query/amend the session data outside of an HTTP request.
=> Add an implementation of ISession{Store} for testing

src/Dfc.CourseDirectory.Core/Models/ApprenticeshipDeliveryMode.cs, src/Dfc.CourseDirectory.Core/Models/ApprenticeshipLocationType.cs, src/Dfc.CourseDirectory.Core/Models/ApprenticeshipQAStatus.cs, src/Dfc.CourseDirectory.Core/Models/ApprenticeshipQAUnableToCompleteReasons.cs, src/Dfc.CourseDirectory.Core/Models/CourseDeliveryMode.cs, src/Dfc.CourseDirectory.Core/Models/ProviderType.cs, src/Dfc.CourseDirectory.WebV2/Features/ApprenticeshipQA/ApprenticeshipAssessment.cshtml, src/Dfc.CourseDirectory.WebV2/Features/ApprenticeshipQA/ListProviders.cshtml, src/Dfc.CourseDirectory.WebV2/Features/ApprenticeshipQA/ProviderSelected.cshtml, src/Dfc.CourseDirectory.WebV2/Features/ApprenticeshipQA/Report.cs, src/Dfc.CourseDirectory.WebV2/Features/DeleteCourseRun/View.cshtml, src/Dfc.CourseDirectory.WebV2/Features/NewApprenticeshipProvider/ApprenticeshipSummary.cshtml, src/Dfc.CourseDirectory.WebV2/Features/NewApprenticeshipProvider/ProviderDetailConfirmation.cshtml, src/Dfc.CourseDirectory.WebV2/Features/Providers/ProviderDetails.cshtml, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/ApprenticeshipQA/QAStatusReportTests.cs
'Display name' now means something else in our world (i.e. the _label_
for a Provider) so remove the overloaded term.
=> Rename the ToDisplayName extension methods to ToDescription

src/Dfc.CourseDirectory.Core/DataStore/Sql/BulkCopyHelper.cs, src/Dfc.CourseDirectory.Core/Dfc.CourseDirectory.Core.csproj, src/Dfc.CourseDirectory.Core/SqlDataSync.cs
- Remove the command timeout for bulk copying.
- Reduce the size of records synced in a single transaction.
=> Apprenticeship SQL sync timeout fixes

src/Dfc.CourseDirectory.Core/Connected Services/UkrlpService/ConnectedService.json, src/Dfc.CourseDirectory.Core/Connected Services/UkrlpService/Reference.cs, src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/Models/Provider.cs, src/Dfc.CourseDirectory.Core/ReferenceData/Ukrlp/IUkrlpWcfClientFactory.cs, src/Dfc.CourseDirectory.Core/ReferenceData/Ukrlp/UkrlpService.cs, src/Dfc.CourseDirectory.Core/ReferenceData/Ukrlp/UkrlpSyncHelper.cs, src/Dfc.CourseDirectory.Core/ReferenceData/Ukrlp/UkrlpWcfClientFactory.cs, src/Dfc.CourseDirectory.Core/ReferenceData/Ukrlp/WcfConfiguration.cs, src/Dfc.CourseDirectory.Functions/Startup.cs, src/Dfc.CourseDirectory.Functions/SyncUkrlp.cs, src/Dfc.CourseDirectory.Web/Startup.cs, tests/Dfc.CourseDirectory.Core.Tests/Dfc.CourseDirectory.Core.Tests.csproj, tests/Dfc.CourseDirectory.Core.Tests/ReferenceDataTests/TestUkrlpWcfClientFactory.cs, tests/Dfc.CourseDirectory.Core.Tests/ReferenceDataTests/UkrlpResponse.xml, tests/Dfc.CourseDirectory.Core.Tests/ReferenceDataTests/UkrlpServiceTests.cs, tests/Dfc.CourseDirectory.Core.Tests/ReferenceDataTests/UkrlpSyncHelperTests.cs, tests/Dfc.CourseDirectory.Testing/TestData/TestData.CreateProvider.cs
See individual commit messages for detailed changes. The commits:
* add missing regression tests to the two main classes in the UKRLP client
* and then upgrade the client
* and then update the tests to match.
* Plus some minor cleanup and logging.
This change affects:
- The azure function app `SyncUkrlpChanges`
- The sign-in to the website (which syncs a single provider)
Here's a representative example of how the xml structure changed between the versions:
Here's the new output from the function app:
```
[24/09/2020 12:47:51] Executing 'SyncUkrlpChanges' (Reason='This function was programmatically called via the host APIs.', Id=27e4ff95-ad4b-4763-8021-25e6c1ea6426)                           
[24/09/2020 12:47:51] UKRLP Sync: Beginning SyncAllProviderData, fetching providers from UKRLP …
```
=> Update UKRLP client from v3 to v6 (take 2)

src/Dfc.CourseDirectory.Core/Dfc.CourseDirectory.Core.csproj, src/Dfc.CourseDirectory.Core/SqlDataSync.cs
We have intermittent errors running this and the errors are proving difficult to nail down. For a one-time sync, retrying a few times per batch should this execute successfully.
=> Add retries to SyncAllApprenticeships

.editorconfig
Editorconfig - add final newline
Because git and github complain if you don't which is minorly annoying.
=> Editorconfig - add final newline

src/Dfc.CourseDirectory.WebV2/SharedViews/Components/AdminProviderContextNav.cshtml, src/Dfc.CourseDirectory.WebV2/SharedViews/Components/AdminProviderContextNavViewComponent.cs, src/Dfc.CourseDirectory.WebV2/SharedViews/Components/AdminTopNav.cshtml, src/Dfc.CourseDirectory.WebV2/SharedViews/Components/ProviderNavViewModel.cs, src/Dfc.CourseDirectory.WebV2/SharedViews/Components/ProviderTopNav.cshtml, src/Dfc.CourseDirectory.WebV2/SharedViews/Components/ProviderTopNavViewComponent.cs, tests/Dfc.CourseDirectory.WebV2.Tests/LayoutTests.cs
- Converted tests to use FluentAssertions and use testid attributes
instead of labels.
=> PTCD-683 Standardise nav links and order

src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/Queries/UpdateApprenticeship.cs, src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/Queries/UpdateProviderFromUkrlpData.cs, src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/Queries/UpdateProviderInfo.cs, src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/QueryHandlers/UpdateApprenticeshipHandler.cs, src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/QueryHandlers/UpdateProviderFromUkrlpDataHandler.cs, src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/QueryHandlers/UpdateProviderInfoHandler.cs, tests/Dfc.CourseDirectory.Testing/DataStore/CosmosDb/QueryHandlers/UpdateApprenticeshipHandler.cs, tests/Dfc.CourseDirectory.Testing/DataStore/CosmosDb/QueryHandlers/UpdateProviderFromUkrlpDataHandler.cs, tests/Dfc.CourseDirectory.Testing/DataStore/CosmosDb/QueryHandlers/UpdateProviderInfoHandler.cs
Some of the older DB commands that update data have the signature `IDbCommand<Success>` and they either explode if the specified thing doesn't exist or silently do nothing.
For new commands we've settled on `IDbCommand<OneOf<NotFound, Success>>` so we can consistently return the 'not found'-ness.
This commit brings the older commands into line with the new ones.
=> Db command signature consistency

src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/Models/Course.cs, src/Dfc.CourseDirectory.Functions/FixCorruptStatusData.cs
Add Azure Function for fixing corrupt course status data
The source of the corruption has already been fixed in https://github.com/SkillsFundingAgency/dfc-providerportal-courses/pull/171
Test locally with
```bash
curl -v http://localhost:7071/admin/functions/FixCorruptStatusData -d "{}" -H "Content-Type:application/json"
```
[PTCD-636](https://skillsfundingagency.atlassian.net/browse/PTCD-636)
=> [PTCD-636] Add Azure Function for fixing corrupt course status data

src/Dfc.CourseDirectory.Core/SqlDeployHelper.cs
Stores a hash of the dacpac in APPDATA and only deploys if the new hash is different from the old one (i.e. the dacpac has been rebuilt).
On my machine this reduces the initialization time for tests from around 7s to 3s.
=> Don't redeploy test database if the DACPAC is unchanged

src/Dfc.CourseDirectory.Core/Validation/Rules.cs
Updated V2 Website validation to require domain (host) with at least one top-level domain
=> PTCD-716 Fix Website Domain Validation

src/Dfc.CourseDirectory.WebV2/Features/BulkUpload/BulkUploadController.cs, src/Dfc.CourseDirectory.WebV2/Features/NewApprenticeshipProvider/NewApprenticeshipProviderController.cs, src/Dfc.CourseDirectory.WebV2/Filters/RedirectToProviderSelectionActionFilter.cs, src/Dfc.CourseDirectory.WebV2/RequireProviderContextAttribute.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FilterTests/RedirectToProviderSelectionActionFilterTests.cs
Other attributes, including those in ASP.NET, use 'require' not 'requires'.
=> Drop the 's' from 'Requires' in RequiresProviderContextAttribute

src/Dfc.CourseDirectory.Web/Controllers/CourseSummaryController.cs
Cope gracefully with missing venue
We have some bad data that means venueIds are referenced that don't exist. The venue endpoint returns an empty body, which then becomes null, which then throws a null-ref exception which isn't very helpful.
By just not setting the value if it's null the page now loads and the user can correct the corrupted data.
Also corrected use of async.
(hidden by generic error on other envs)
click change...
=> [PTCD-592] Cope gracefully with missing venue

src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/UpsertApprenticeshipsFromCosmos.cs, src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/UpsertCoursesFromCosmos.cs, src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/UpsertProvidersFromCosmos.cs, src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/UpsertVenuesFromCosmos.cs, src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/UpsertApprenticeshipsFromCosmosHandler.cs, src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/UpsertCoursesFromCosmosHandler.cs, src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/UpsertProvidersFromCosmosHandler.cs, src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/UpsertVenuesFromCosmosHandler.cs, src/Dfc.CourseDirectory.Core/SqlDataSync.cs, src/Dfc.CourseDirectory.Database/Pttcd/Tables/Apprenticeships.sql, src/Dfc.CourseDirectory.Database/Pttcd/Tables/Courses.sql, src/Dfc.CourseDirectory.Database/Pttcd/Tables/Providers.sql, src/Dfc.CourseDirectory.Database/Pttcd/Tables/Venues.sql, tests/Dfc.CourseDirectory.Core.Tests/SqlDataSyncTests.cs
We have some invalid data in our SQL tables currently due to some hard deletes on Cosmos data (the hard deletes have since been fixed). By adding this column so we can identify those records that no longer exist in Cosmos after we re-run the 'sync all' processes and seeing which records haven't been updated.
It also may be useful for the forthcoming Azure Search indexer as the 'high water mark' column (https://docs.microsoft.com/en-us/azure/search/search-howto-connecting-azure-sql-database-to-azure-search-using-indexers#high-water-mark-change-detection-policy)
=> Add a LastSyncedFromCosmos column to SQL tables

src/Dfc.CourseDirectory.Web/Views/Report/Index.cshtml, src/Dfc.CourseDirectory.Web/Views/SearchProvider/Index.cshtml, src/Dfc.CourseDirectory.Web/Views/_ViewImports.cshtml, src/Dfc.CourseDirectory.WebV2/Features/ApprenticeshipQA/_ViewStart.cshtml, src/Dfc.CourseDirectory.WebV2/Features/HelpdeskDashboard/_ViewStart.cshtml, src/Dfc.CourseDirectory.WebV2/SharedViews/AdminTopNavSection.cs, src/Dfc.CourseDirectory.WebV2/SharedViews/Components/AdminTopNav.cshtml, src/Dfc.CourseDirectory.WebV2/SharedViews/ViewContextExtensions.cs
Fixes the QA link not being active after splitting the controller.
=> Use an enum & helper method for setting the active admin nav link

src/Dfc.CourseDirectory.Core/SqlDataSync.cs, src/Dfc.CourseDirectory.Functions/ImportLarsData.cs, src/Dfc.CourseDirectory.Functions/RemoveZombieCoursesFromSql.cs, src/Dfc.CourseDirectory.Functions/SyncCosmosCollectionsToSql.cs, src/Dfc.CourseDirectory.Functions/SyncUkrlp.cs
These were added to Cosmos then hard deleted so our sync process didn't see' their removal. This uses the new LastSyncedFromCosmos column for figuring out what to delete (which will always be null for these zombie courses). A full sync 'SyncCoursesCosmosCollectionToSql' should be run before running this to ensure legit entries have the LastSyncedFromCosmos column populated.
=> PTCD-756 Add a temporary cleanup function for removing zombie courses from SQL

src/Dfc.CourseDirectory.Web/Controllers/ProviderController.cs, src/Dfc.CourseDirectory.WebV2/Features/DeleteCourseRun/DeleteCourseRunController.cs, src/Dfc.CourseDirectory.WebV2/Features/EditVenue/EditVenueController.cs, src/Dfc.CourseDirectory.WebV2/Features/ProviderDashboard/ProviderDashboardController.cs, src/Dfc.CourseDirectory.WebV2/Features/Providers/ProvidersController.cs, src/Dfc.CourseDirectory.WebV2/Middleware/ProviderContextMiddleware.cs
The AssignLegacyProviderContextAttribute exists to ensure that transitioning from a v2 page (which doesn't require the session-based provider context) to a legacy page (which does) will work correctly and the 'ambient' provider is correct.
This attribute has been sprinkled over selected actions where there have been visible bugs. However, given that the layout produces links to legacy pages we should *always* been assigning this where we can. This commit makes that change.
The AssignLegacyProviderContextAttribute is kept around for the day when the layout no longer links to any legacy pages. At such a time this change can be reverted.
=> Always assign legacy provider context where possible

src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/Models/Venue.cs
Had to ask on slack why there were two version of email in prod
differing only by case.
> "That is known issue in Cosmos for venues migrated from Tribal. Front
> end uses PHONE, EMAIL and WEBSITE. Telephone, Email and Website are
> added by migration but both will have same data.  If venue is edited and
> saved again, Telephone, Email and Website will disappear."
> ~ Narahari Miriyala
* Also Spaced out fields for readability as some have attributes and some don't.
=> Document dead venue fields

src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/Queries/UpdateVenue.cs, src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/QueryHandlers/UpdateVenueHandler.cs, src/Dfc.CourseDirectory.Services/Models/Venues/Venue.cs, src/Dfc.CourseDirectory.Web/Controllers/VenuesController.cs, src/Dfc.CourseDirectory.Web/SqlDataSyncExtensions.cs, src/Dfc.CourseDirectory.WebV2/Features/EditVenue/Save.cs, src/Dfc.CourseDirectory.WebV2/ServiceCollectionExtensions.cs, tests/Dfc.CourseDirectory.Testing/DataStore/CosmosDb/QueryHandlers/UpdateVenueHandler.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/EditVenue/SaveTests.cs
The CFL lag means we cannot build a journey that includes any venue
additions/modifications and use SQL for the data source. If we force a
sync for the updated record synchronously then we can successfully 'read
our writes'.
=> Sync Venues to SQL immediately after Cosmos change

src/Dfc.CourseDirectory.Services/Models/Enums.cs, tests/Dfc.CourseDirectory.Testing/DataStore/CosmosDb/QueryHandlers/GetApprenticeshipsByIdsHandler.cs
Use enum values in Testing DataStore GetApprenticeshipsByIdsHandler
Just a suggestions, I might have missed a reason why we're not doing this.
=> Use enum values in Testing DataStore GetApprenticeshipsByIdsHandler

tests/Dfc.CourseDirectory.Testing/TestData/TestData.CreateVenue.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/Apprenticeships/ClassroomLocationTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DeleteCourseRunTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/EditVenue/AddressTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/EditVenue/CommonVenueTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/EditVenue/DetailsTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/EditVenue/EmailTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/EditVenue/NameTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/EditVenue/PhoneNumberTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/EditVenue/SaveTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/EditVenue/WebsiteTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/NewApprenticeshipProvider/ApprenticeshipEmployerLocationsRegionsTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/NewApprenticeshipProvider/ApprenticeshipEmployerLocationsTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/NewApprenticeshipProvider/ApprenticeshipSummaryTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/NewApprenticeshipProvider/FlowModelInitializerTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FilterTests/AuthorizeVenueAttributeTests.cs
Refactor - return full Venue from TestData creation
Fixup usages:
* Remove unused venueId variables.
* Pluck Id out for all exisiting usages.
This allows using default values for the generated Venue in the rest of a test without doing another round-trip to fetch the entity.
=> Refactor - return full Venue from TestData creation

src/Dfc.CourseDirectory.WebV2/Features/Error/ErrorController.cs, src/Dfc.CourseDirectory.WebV2/Settings.cs, tests/Dfc.CourseDirectory.WebV2.Tests/CourseDirectoryApplicationFactory.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/ErrorTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FilterTests/RestrictProviderTypesAttributeTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/Startup.cs
By default TestServer allows unhandled exceptions to bubble up to the Request sender (HttpClient.SendAsync in our case). This is useful for debugging test failures since you get the stack trace from the source exception in failure messages instead of the stack trace from HttpResponseMessage.EnsureSuccessCode (or similar). Our custom error handling is masking this, however.
Given that we don't rely on our custom error behaviours in our tests (indeed we disable one of its behaviours) turn off custom errors for tests.
=> Improve debuggability of integration tests

Directory.Build.props
We want to use this for annotating old/legacy code that we shouldn't be
touching but 'warnings as errors' means build fails. Add an exception
for the obsolete error diagnostic codes. If [Obsolete(error = true)] is
used then build will still fail with an error.
=> Don't fail the build if referencing [Obsolete] code

CourseDirectory.All.sln.DotSettings
To stop Jetbrains' Rider complaining about the spelling of UKPRN (United Kingdom Provider Reference Number)
=> Add UKPRN to Rider acronym list

tests/Dfc.CourseDirectory.Testing/TestData/TestData.CreateApprenticeship.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/ApprenticeshipQA/ApprenticeshipAssessmentTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/ApprenticeshipQA/CompleteTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/ApprenticeshipQA/ListProvidersTest.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/ApprenticeshipQA/ProviderApprenticeshipQAInfoPanelTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/ApprenticeshipQA/ProviderAssessmentTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/ApprenticeshipQA/ProviderSelectedTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/ApprenticeshipQA/QAStatusReportTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/ApprenticeshipQA/StatusTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/NewApprenticeshipProvider/ApprenticeshipSummaryTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/NewApprenticeshipProvider/FlowModelInitializerTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/NewApprenticeshipProvider/HidePassedNotificationTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/NewApprenticeshipProvider/QANotificationsTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FilterTests/AuthorizeApprenticeshipAttributeTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FilterTests/VerifyApprenticeshipIdAttributeTests.cs
Refactor TestData to return newly created Apprenticeship
To save me an extra round-trip in the test I'm writing in branch PTCD-754-fixup-apprenticeship-venue-corruption.
=> Refactor TestData to return newly created Apprenticeship

src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/SetProviderDisplayNameSourceHandler.cs
Now that FindACourseIndex table is updated via a trigger the row count from a single row update is no longer necessarily 1. Invert the condition in this handler to account for this.
=> Fix SetProviderDisplayNameSourceHandler return value

src/Dfc.CourseDirectory.Core/DataStore/Sql/ServiceCollectionExtensions.cs
1465e321d1583b33e5a85529e591fff4bc291988 reduced the isolation level from `Snapshot` to `ReadCommitted` (to resolve deadlocking). This isolation level is not quite strong enough and we're seeing intermittent sync issues with the FAC index table which look to be solved by moving to `RepeatableRead`.
=> Change default isolation level to RepeatableRead

src/Dfc.CourseDirectory.Functions/local.settings.json
Otherwise they start running when you `func start` locally which is disruptive and possibly will mess with data you care about.
https://docs.microsoft.com/en-us/azure/azure-functions/disable-function#localsettingsjson
=> Disable TimerTrigger function apps for local development

src/Dfc.CourseDirectory.WebV2/Features/Providers/EditProviderType.cs, src/Dfc.CourseDirectory.WebV2/Features/Providers/EditProviderTypeConfirm.cshtml, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/Providers/EditProviderTypeTests.cs
Updated EditProviderTypeConfirm to use checksum of affected T Level ids instead of raw ids
This change simplifies the data structure used to ascertain any changes to affected T Levels in an effort to reduce the POST payload size and as such the risk of tripping over a WAF rule, and to make modification of the checksum generation simpler in the event a conflicting WAF rule is found.
Based on an estimated maximum number of T Levels per provider of 240, the size of the checksum will be 5120 bytes, which should not conflict with existing WAF rules.
=> PTCD-795 Update EditProviderTypeConfirm Checksum

src/Dfc.CourseDirectory.WebV2/AddressSearch/GetAddressAddressSearchService.cs, tests/Dfc.CourseDirectory.WebV2.Tests/AddressSearch/GetAddressAddressSearchServiceTests.cs
`GetHashCode()` is not guaranteed across multiple .NET processes, and thus can potentially fail in a multi-server environment.
https://docs.microsoft.com/en-us/dotnet/api/system.string.gethashcode?view=netcore-3.1
=> Fixed GetAddressAddressSearchService ID Generation

src/Dfc.CourseDirectory.Services/Models/Venues/Venue.cs
Reproduce by selecting Buckingham Palace SW1A 1AA which has no `address1` when creating a new venue in the provider facing website.
Triggering the exception:
The user won't see this message, they'll just get the generic 500 page, but it'll be easier to understand the logs with a better message. The journey is to be fixed properly at some point so this is a stop-gap.
=> Better exception messages for missing required Venue fields

src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/QueryHandlers/GetVenueByIdHandler.cs, src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/QueryHandlers/GetVenuesByProviderHandler.cs
As discussed on slack, there is no use case for returning archived Venues
Resurrection of original PR: https://github.com/SkillsFundingAgency/dfc-coursedirectory/pull/1869 and extended following analysis of impact to changes.
The only potential issue we might see is on FAC where an active course has an Archived Venue attached to it, in which case we'll need to fix the data and establish how that came to be.
=> Filter Out Archived Venues in DataStore.Cosmos Handlers

src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/GetLiveTLevelsReport.cs, src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/GetLiveTLevelsReportHandler.cs, src/Dfc.CourseDirectory.WebV2/Features/TLevels/Reporting/LiveTLevelsReport.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/TLevels/Reporting/LiveTLevelsReportTests.cs
Update Live T Levels Report to read data from Pttcd.FindACourseIndex
This is a bit of future-proofing to avoid the need to maintain the Live T Levels Report query in line with the rules applied to the FAC index. (As of course, this report should be representative of the data in the FAC index.)
Can't ship until #1870 is merged.
=> PTCD-793 Live T Levels Report Use FindACourseIndex Table

src/Dfc.CourseDirectory.Web/ViewComponents/SearchProviderResults/Default.cshtml, src/Dfc.CourseDirectory.Web/ViewModels/SearchProvider/SearchProviderResultViewModel.cs
CourseDirectoryName is an old thing that's not always populated, leading
to empty columns in the Provider Search UI. Provider Name will always be
populated (via UKRLP) and is what we want to show here.
=> PTCD-603 Use ProviderName instead of CourseDirectoryName in search results

src/Dfc.CourseDirectory.Web/Controllers/ApprenticeshipsController.cs, src/Dfc.CourseDirectory.Web/Views/Apprenticeships/Complete/Index.cshtml
* Update add-apprenticeship-published to new design system and make 2/3 width.
* Update copy/links/layout to match prototype (with new content from Clair, see ticket).
* Null-proof the page so it doesn't explode when refreshed (still loses the name, but slightly less bad UX now).
[PTCD-822](https://skillsfundingagency.atlassian.net/browse/PTCD-822)
=> [PTCD-822] Update add-apprenticeship-published designs

src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/QueryHandlers/CreateApprenticeshipHandler.cs, src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/QueryHandlers/UpdateApprenticeshipHandler.cs, src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/QueryHandlers/UpdateProviderInfoHandler.cs, src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/QueryHandlers/UpdateVenueHandler.cs, tests/Dfc.CourseDirectory.Testing/DataStore/CosmosDb/QueryHandlers/CreateApprenticeshipHandler.cs, tests/Dfc.CourseDirectory.Testing/DataStore/CosmosDb/QueryHandlers/CreateCourseHandler.cs, tests/Dfc.CourseDirectory.Testing/DataStore/CosmosDb/QueryHandlers/UpdateApprenticeshipHandler.cs, tests/Dfc.CourseDirectory.Testing/DataStore/CosmosDb/QueryHandlers/UpdateProviderInfoHandler.cs, tests/Dfc.CourseDirectory.Testing/DataStore/CosmosDb/QueryHandlers/UpdateVenueHandler.cs
As per discussions around [PTCD-563](https://skillsfundingagency.atlassian.net/browse/PTCD-563) etc.
This will be stable in the face of changes in a user's email address in DfE Sign-in, and also avoids storing any extra copies of personally identifiable information.
This is probably not everything but it was the things that were easy to find in a limited time.
=> Use UserId for audit fields instead of email

src/Dfc.CourseDirectory.Web/Views/Apprenticeships/Complete/Index.cshtml
[PTCD-846](https://skillsfundingagency.atlassian.net/browse/PTCD-846)
Add apprenticeship journey, "published" page.
Changed because you can't copy an apprenticeship.
After:
=> [PTCD-846] Copytext change for edit apprenticeship link

Dfc.CourseDirectory/Resources/AzureSearch/SearchDatasource.json, Dfc.CourseDirectory/Resources/AzureSearch/SearchIndex.json, Dfc.CourseDirectory/Resources/AzureSearch/SearchIndexer.json, src/Dfc.CourseDirectory.Database/Dfc.CourseDirectory.Database.sqlproj, src/Dfc.CourseDirectory.Database/Pttcd/Views/vwProviderSearchIndex.sql
Create a new azure-search index (aka azure cognitive search) for the list of providers.
This is a sub-task of [PTCD-841](https://skillsfundingagency.atlassian.net/browse/PTCD-841)
The intention is to deploy the two indexes side-by-side with this PR; then in future work move the calling code over and then remove the old index.
(from second commit)
This is index not being kept compatible with the existing search index so when we switch calls over to this the models will need to be updated.  I think the switch to a replacement index is a convenient moment to eliminate the arbitrary variation in naming, unused fields, and confusing mappings.
Note that the "status" field names are confusing, in this version I've opted to keep the names aligned with those in the sql table as I think that will …
=> [PTCD-823] New provider-search SQL view and azure search index

src/Dfc.CourseDirectory.Database/Pttcd/Views/vwProviderSearchIndex.sql
This fixes the subquery to ProviderContacts and pulls in the best approximation of "town" that we currently have.
=> Include town/postcode in new providers search index

src/Dfc.CourseDirectory.Web/Controllers/MigrationController.cs, src/Dfc.CourseDirectory.Web/Controllers/PublishCourses/PublishCoursesController.cs, src/Dfc.CourseDirectory.Web/Helpers/VenueHelper.cs
This is one of a few changes needed to bypass the obsolete venue microservice and go direct to cosmos for venue data.
This change is not dependent on the other work in progress or the other changes so is a separate PR.
=> [PTCD-866] Switch VenueHelper to direct-to-cosmos

src/Dfc.CourseDirectory.Core/Search/Models/Provider.cs, src/Dfc.CourseDirectory.Web/appsettings.json, src/Dfc.CourseDirectory.WebV2/Features/ProviderSearch/ProviderSearch.cs, src/Dfc.CourseDirectory.WebV2/ServiceCollectionExtensions.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/ProviderSearch/ProviderSearchTests.cs
* Update provider search model to match new index -  This makes the field names consistent all the way down to the data store.
* Configure provider search to use new index. - New index is "providers", old is "provider".
* Config key name changed to avoid being overridden by any existing production configuration.
Depends on #1944
[PTCD-864](https://skillsfundingagency.atlassian.net/browse/PTCD-864)
=> PTCD-864 Use new sql-based provider search index

src/Dfc.CourseDirectory.Web/Controllers/BulkUploadController.cs, src/Dfc.CourseDirectory.Web/ViewModels/BulkUpload/PublishCompleteViewModel.cs
The assignment of this is causing NullReferenceExceptions in a lot of cases and it's not used.
=> PTCD-891 Remove redundant VM property

src/Dfc.CourseDirectory.Services/BulkUploadService/BulkUploadService.cs, src/Dfc.CourseDirectory.Services/VenueService/VenueSearchCriteria.cs, src/Dfc.CourseDirectory.Services/VenueService/VenueService.cs, src/Dfc.CourseDirectory.Web/ApprenticeshipBulkUpload/ApprenticeshipBulkUploadService.cs, src/Dfc.CourseDirectory.Web/Controllers/CopyCourse/CopyCourseRunController.cs, src/Dfc.CourseDirectory.Web/Controllers/ProviderController.cs, src/Dfc.CourseDirectory.Web/Controllers/ProviderCourses/ProviderCoursesController.cs, src/Dfc.CourseDirectory.Web/Controllers/YourCoursesController.cs, src/Dfc.CourseDirectory.Web/Helpers/VenueSearchHelper.cs, src/Dfc.CourseDirectory.Web/ViewComponents/RequestModels/VenueSearchRequestModel.cs
A smaller piece of the overall bypass of `IVenueService`.
Removing this is only possible with the work on branch `PTCD-832-add-venue`, without that this doesn't compile so we can't go straight to `main` with this cleanup.
Ideally we'd merge this on the way to make the final removal a smaller patch to comprehend. The existence of the is extra unused search criteria makes the code to be removed harder to follow.
[PTCD-866](https://skillsfundingagency.atlassian.net/browse/PTCD-866)
=> PTCD-866 Remove unused `NewAddressId

src/Dfc.CourseDirectory.Services/VenueService/IVenueService.cs, src/Dfc.CourseDirectory.Services/VenueService/VenueService.cs
A smaller piece of the overall bypass of `IVenueService`.
Removing this is only possible with the work on branch `PTCD-832-add-venue` which removes the final reference to this method, without that this doesn't compile so we can't go straight to `main` with this cleanup.
[PTCD-866](https://skillsfundingagency.atlassian.net/browse/PTCD-866)
=> PTCD-866 Remove unused GetVenuesByPRNAndNameAsync

src/Dfc.CourseDirectory.Core/DataStore/Sql/ISqlQueryDispatcher.cs, src/Dfc.CourseDirectory.Core/DataStore/Sql/ServiceProviderSqlDispatcherFactory.cs, src/Dfc.CourseDirectory.Core/ReferenceData/Lars/LarsDataImporter.cs, src/Dfc.CourseDirectory.Core/SqlDataSync.cs, tests/Dfc.CourseDirectory.Testing/DatabaseFixture.cs, tests/Dfc.CourseDirectory.Testing/SqlQuerySpy.cs, tests/Dfc.CourseDirectory.Testing/TestData/TestData.cs, tests/Dfc.CourseDirectory.WebV2.Tests/TestUserInfo.cs
Currently we expose `SqlTransaction` then callers can say `Transaction.Commit()`. SqlTransaction is not very mock friendly, however. This is step one in improving this type's mockability.
Removing `SqlTransaction` is the ultimate goal here but we have various places that rely on it. That change is for another day.
=> Expose Commit() on ISqlQueryDispatcher

src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/Queries/UpdateProviderBulkUploadStatus.cs, src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/QueryHandlers/UpdateProviderBulkUploadStatusHandler.cs, src/Dfc.CourseDirectory.Services/BulkUploadService/BulkUploadService.cs, src/Dfc.CourseDirectory.Services/BulkUploadService/IBulkUploadService.cs, src/Dfc.CourseDirectory.Web/Controllers/BulkUploadController.cs, src/Dfc.CourseDirectory.Web/Startup.cs
As part of moving away from Cosmos & micro-services we need to remove
usage of the fileprocessor. The sole remaining use of this is for large
FE Bulk Upload files. This commit prevents fileprocessor from processing
these large files (by appending a suffix to files uploaded to Blob
Storage) and instead does the processing in-proc, using our background
worker bits.
The code is the bare minimum to make this work only, given that all this
is going away soon.
=> PTCD-964 Decouple fileprocessor

src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/UpdateFindACourseIndexForVenues.cs, src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/PublishVenueUploadHandler.cs, src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/UpdateFindACourseIndexForVenuesHandler.cs, src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/UpdateVenueHandler.cs, src/Dfc.CourseDirectory.Database/Pttcd/StoredProcedures/RefreshFindACourseIndex.sql, src/Dfc.CourseDirectory.Database/Pttcd/StoredProcedures/RefreshFindACourseIndexForTLevels.sql, src/Dfc.CourseDirectory.Database/Pttcd/Tables/FindACourseIndex.sql, src/Dfc.CourseDirectory.Database/Pttcd/Triggers/TRG_Venues_UpdateFindACourseIndex.sql, src/Dfc.CourseDirectory.Functions/UpdateFindACourseIndexVenueId.cs
The previous trigger-based update was slow due to its row-by-row update.
This change removes the trigger in favour of a more explicit command
that passes the amended venue IDs.
=> Optimise FAC index updates when venues are changed part 2

src/Dfc.CourseDirectory.Core/DataManagement/FileUploadProcessor.Venues.cs, src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/SetVenueUploadProcessing.cs, src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/SetVenueUploadProcessingHandler.cs, tests/Dfc.CourseDirectory.Core.Tests/DataManagementTests/FileUploadProcessorTests.Venues.cs
For some reason some venue uploads are being picked up by the function app multiple times. This is resulting in some already-abandoned uploads coming back to life as well as making our audit timestamps very strange (e.g. processing started *after* processing completed).
This change adds a check so we don't attempt to re-process files after they've already been processed and it deletes the blob after processing.
=> Prevent venue uploads from being processed multiple times

src/Dfc.CourseDirectory.Core/DataManagement/FileUploadProcessor.Venues.cs, src/Dfc.CourseDirectory.Core/DataManagement/IFileUploadProcessor.cs, src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Venues/DeleteRow.cs, src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Venues/DeleteRow.cshtml, src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Venues/VenuesDataManagementController.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Venues/DeleteRowTests.cs
The previous implementation did a separate call to figure out whether the Upload still had errors outside of the transaction that deleted the row. In general, we don't want to multiple database transactions for a given request. This commit changes the signature so that the `Delete` method returns the new `UploadStatus`. It now throws if the specified row doesn't exist.
=> Amend FileUploadProcessor.DeleteVenueUploadRowForProvider signature

src/Dfc.CourseDirectory.Core/DataManagement/FileUploadProcessor.Courses.cs, tests/Dfc.CourseDirectory.Core.Tests/DataManagementTests/CourseUploadRowValidatorTests.cs
A separate story covers pre-validating LARS code before the upload is saved.
=> Remove LARS code validation from course upload post-processing

src/Dfc.CourseDirectory.Core/DataManagement/ParsedCsvCourseRow.cs, src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/GetCoursesForProviderHandler.cs, src/Dfc.CourseDirectory.Core/SqlDataSync.cs, src/Dfc.CourseDirectory.Functions/NormalizeClassroomBasedCourseRunFields.cs
The Cosmos model uses 0, the SQL model should be using null. This fixes
the Cosmos->SQL sync to map 0 to null, the one SQL query we have that
uses this field and adds a Function to clear up the data.
=> Normalize 0 for CourseStudyMode and CourseAttendancePattern to null

src/Dfc.CourseDirectory.Database/Pttcd/Tables/Apprenticeships.sql, src/Dfc.CourseDirectory.Functions/AddMissingProviderIdForeignKeys.cs
There's some junk data that means the FK is failing. Also amended the FK fixup script to fix this bad data so we can re-apply FK later.
=> Temporarily remove the ProviderId FK on Apprenticeships

src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/GetCourse.cs, src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/GetCourseHandler.cs, tests/Dfc.CourseDirectory.Testing/DataStore/CosmosDb/Queries/CreateCourse.cs, tests/Dfc.CourseDirectory.Testing/DataStore/CosmosDb/QueryHandlers/CreateCourseHandler.cs, tests/Dfc.CourseDirectory.Testing/TestData/TestData.CreateCourse.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/BulkUpload/BulkUploadTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Courses/DownloadTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DeleteCourseRunTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/ProviderDashboard/DashboardTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/Providers/Reporting/ProviderMissingPrimaryContactReportTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/Providers/Reporting/ProviderTypeReportTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/Venues/DeleteVenue/DeleteVenueTests.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FilterTests/AuthorizeCourseAttributeTests.cs
There's now a method on CreateCourseCourseRun for each delivery type that accepts only the relevant/allowed parameters for that delivery type.
Also amended the method to return the Course SQL model instead of the Cosmos one.
=> Amend TestData.CreateCourse to ensure we're creating valid CourseRuns

src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/CourseMappingHelper.cs, src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/GetCourseHandler.cs, src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/GetCoursesForProviderHandler.cs, src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/PublishCourseUploadHandler.cs, src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/UpsertCoursesFromCosmosHandler.cs, src/Dfc.CourseDirectory.Database/Pttcd/Tables/CourseRuns.sql, src/Dfc.CourseDirectory.Database/Pttcd/Tables/Courses.sql
The legacy UI stores string fields HTML-encoded in Cosmos. As part of the move away from Cosmos we want to move away from encoding data at rest and encoding it 'on the edge' as appropriate. 
This PR adds an additional field to the `Courses` and `CourseRuns` SQL tables indicating whether that row has its strings encoded or not.
All existing data will have the flag set to `1` since it's currently all synced from Cosmos. As we move the UI to using SQL directly we will store things unencoded and the flag will be set to `0`. The new Course Data Management features store fields unencoded also.
The mapping to `Course` and `CourseRun` models is updated here to handle both cases; where the data is encoded and where it's not.
=> Rationalize HTML encoded course data

src/Dfc.CourseDirectory.FindACourseApi/Features/CourseRunDetail/CourseRunDetail.cs, src/Dfc.CourseDirectory.FindACourseApi/Features/Search/Search.cs, src/Dfc.CourseDirectory.FindACourseApi/Features/TLevels/TLevelDetail.cs, tests/Dfc.CourseDirectory.FindACourseApi.Tests/FeatureTests/TLevelDetailTests.cs
The front-end is expecting these fields to be HTML encoded. Originally
they were encoded before entry into Cosmos but now we're moving away
from that we need to encode 'on the edge'.
=> HTML encode free text fields on FAC API

src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/UpdateFindACourseIndexFromMissingCourses.cs, src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/UpdateFindACourseIndexFromMissingCoursesHandler.cs, src/Dfc.CourseDirectory.Functions/RefreshFindACourseIndex.cs
We're seeing duplicate key exceptions from this job that I think are due
to this process racing with the background task that's indexing
just-published courses. Exclude courses that have been created in the
past hour to allow time for the background task to complete.
=> Exclude just-created courses from FAC index update job

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Venues/Dashboard.cs, tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/DashboardTests.cs
- Updated data management dashboard to stop rendering apprenticeships card until QA passed. Like provider dashboard does.
- Added unit test.
=> SDD-990 - Stop Rendering apprenticeship data management card

src/Dfc.CourseDirectory.Core/DataManagement/FileUploadProcessor.Apprenticeships.cs, src/Dfc.CourseDirectory.Core/Validation/ApprenticeshipValidation/RuleBuilderExtensions.cs, tests/Dfc.CourseDirectory.Core.Tests/DataManagementTests/ApprenticeshipUploadRowValidatorTests.cs
Refactor of standardcode validation rule, so that it allows an apprenticeship classroom/employer to share a standard code. 
- 2 Employer, 2 classroom with same standardcode will error on both employer apprenticeships but not classroom.
- 2 Employer with same standard will error against both employer apprenticeships
- 1 Employer, 1 Classroom with same standardcode will not error
- 1 Employer, 2 classroom with same standardcode will not error
=> SDD-1063 - Refactor Muliple Standard code validation for apprenticeships

Dfc.CourseDirectory.Api/Resources/ArmTemplates/template.json, Dfc.CourseDirectory.FindACourseApi/Resources/ArmTemplates/template.json, Dfc.CourseDirectory/Resources/ArmTemplates/template.json
migrated app should come from the variables as
lower environments does not have a migrated version of the apps.
=> Fixing webapp and functionapp name. Hyphen for
