SkillsFundingAgency/dfc-coursedirectory

README.md
Resources/template.json

Added another Cosmos DB this time with Gremlin API to Azure resources

DASD-4445 Cosmos DB with Gremlin API

---

Resources/parameters.json
Resources/template.json

Add app settings
* VenueAddSettings__ApiUrl
* VenueAddSettings__ApiKey
* VenueAddSettings__ApiVersion

Added app settings v0.4

---

Resources/parameters.json
Resources/template.json

DASD-4525 App settings v0.6

---

Resources/parameters.json
Resources/template.json

Multiple Venue app settings replaced by a single VenueServiceSettings triplet

DASD-4532 App settings v0.7

---

src/Dfc.CourseDirectory.Web/Views/Venues/EditVenueAddress.cshtml
src/Dfc.CourseDirectory.Web/Views/Venues/EditVenueName.cshtml
src/Dfc.CourseDirectory.Web/Views/Venues/VenueAddressSelectionConfirmation.cshtml

text fixes for edit venue

---

Resources/parameters.json
Resources/template.json

Finished changing app settings to v0.8

DASD-4538 App settings v0.8 tidy up

---

src/Dfc.CourseDirectory.Web/Controllers/VenueSearchController.cs
src/Dfc.CourseDirectory.Web/Controllers/VenuesController.cs
src/Dfc.CourseDirectory.Web/ViewComponents/EditVenueAddress/Default.cshtml
src/Dfc.CourseDirectory.Web/ViewComponents/EditVenueAddress/EditVenueAddressModel.cs
src/Dfc.CourseDirectory.Web/ViewComponents/ManualAddress/Default.cshtml
src/Dfc.CourseDirectory.Web/ViewComponents/ManualAddress/ManualAddressModel.cs
src/Dfc.CourseDirectory.Web/ViewComponents/VenueSearchResult/Default.cshtml
src/Dfc.CourseDirectory.Web/ViewComponents/VenueSearchResult/VenueSearchResultModel.cs
src/Dfc.CourseDirectory.Web/ViewModels/VenueAddressSelectionConfirmationViewModel.cs
src/Dfc.CourseDirectory.Web/Views/Venues/AddVenue.cshtml
src/Dfc.CourseDirectory.Web/Views/Venues/AddVenueManualAddress.cshtml
src/Dfc.CourseDirectory.Web/Views/Venues/VenueAddressManualConfirmation.cshtml
src/Dfc.CourseDirectory.Web/Views/Venues/VenueAddressSelectionConfirmation.cshtml

venue bugs

---

src/Dfc.CourseDirectory.Web/ViewComponents/VenueSearchResult/Default.cshtml

Removed CSS that highlighted mouse icon

DFC-5952 - Issue with hover icon

---

src/Dfc.CourseDirectory.Common/Settings/ConfigurationSettings.cs
src/Dfc.CourseDirectory.Web/Startup.cs
src/Dfc.CourseDirectory.Web/ViewComponents/VenueName/Default.cshtml
src/Dfc.CourseDirectory.Web/Views/Venues/Index.cshtml

UI settings injection example

---

Resources/template.json

Updated the call to app service to set the custom hostname

DASD-4289 App service host name

---

Resources/template.json

Added app settings
* AppUISettings__VenueNameComponentSettings__VenueName_Label
* AppUISettings__CourseForComponentSettings__TextFieldMaxChars
* AppUISettings__EntryRequirementsComponentSettings__TextFieldMaxChars
* AppUISettings__WhatWillLearnComponentSettings__TextFieldMaxChars
* AppUISettings__HowYouWillLearnComponentSettings__TextFieldMaxChars
* AppUISettings__WhatYouNeedComponentSettings__TextFieldMaxChars
* AppUISettings__HowAssessedComponentSettings__TextFieldMaxChars
* AppUISettings__WhereNextComponentSettings__TextFieldMaxChars

DASD-4582 App settings v1.0

---

Resources/parameters.json
Resources/template.json

Add CourseServiceSettings__ApiUrl and CourseServiceSettings__ApiKey to app settings

DASD-4615 App settings v1.1

---

src/Dfc.CourseDirectory.Web/Views/Courses/AddCourseSection1.cshtml
src/Dfc.CourseDirectory.Web/wwwroot/css/partials/cd-notifications.css
src/Dfc.CourseDirectory.Web/wwwroot/scss/main.scss
src/Dfc.CourseDirectory.Web/wwwroot/scss/partials/cd-notifications.scss

remove green success and added blue info notification

added notifications

---

src/Dfc.CourseDirectory.Web/Controllers/CoursesController.cs
src/Dfc.CourseDirectory.Web/Views/Courses/AddCourseSection1.cshtml
src/Dfc.CourseDirectory.Web/Views/Courses/AddCourseSection2.cshtml

Remove semicolons, remove unwanted regions, publish button logic changed to account for different delivery modes saving.

Dfc 6907 bug if region not entered

---

src/Dfc.CourseDirectory.Web/Controllers/CoursesController.cs
src/Dfc.CourseDirectory.Web/Extensions/SessionExtensions.cs
src/Dfc.CourseDirectory.Web/ViewComponents/Extensions/ViewComponentExtensions.cs
src/Dfc.CourseDirectory.Web/ViewModels/AddCourseDetailsViewModel.cs
src/Dfc.CourseDirectory.Web/Views/Courses/AddCourseSection2.cshtml

Client side persistence between add course page 1 and page 2.
Also added Preview link

Dfc 6724 client side persistence

---

Resources/template.json

Specify Sku for Azure Search nested template

NCSD-126 Bugfix specify sku

---

src/Dfc.CourseDirectory.Web/Controllers/CoursesController.cs
src/Dfc.CourseDirectory.Web/Views/Courses/AddCourseSection2.cshtml
src/Dfc.CourseDirectory.Web/Views/Courses/SummaryPage.cshtml

DFC-7165-Course name field now persisted between pages
DFC-7164-Duration field now persisted between pages
DFC-7168-Added £ sign to Cost on summary page

Dfc 6983 course summary bugs

---

Resources/parameters.json
Resources/template.json

Added SQL connection string to ARM template as param sqlCourseDirectoryConnectionString

NCSD-206  SQL connection string to ARM template

---

Resources/template.json

Fixed connection string in ARM template

NCSD-206 SQL connection string fix

---

Resources/parameters.json
Resources/template.json

Added CourseTextServiceSettings__* app settings

NCSD-234 App settings v1.4

---

src/Dfc.CourseDirectory.Models/Interfaces/Courses/ICourse.cs
src/Dfc.CourseDirectory.Models/Models/Courses/Course.cs
src/Dfc.CourseDirectory.Web/RequestModels/AddCourseSection1RequestModel.cs
src/Dfc.CourseDirectory.Web/ViewModels/AddCourseDetailsViewModel.cs
src/Dfc.CourseDirectory.Web/ViewModels/AddCourseSummaryViewModel.cs
src/Dfc.CourseDirectory.Web/ViewModels/AddCourseViewModel.cs

DFC-7312 - Change course model frontend

DFC-7311 - Change course model for funding options

---

src/Dfc.CourseDirectory.Web/Controllers/VenuesController.cs

Resolution to updating or adding new venues so that they appear at top

---

src/Dfc.CourseDirectory.Web/Controllers/AddCourseController.cs
src/Dfc.CourseDirectory.Web/RequestModels/AddCourseRequestModel.cs
src/Dfc.CourseDirectory.Web/RequestModels/AddCourseSection1RequestModel.cs
src/Dfc.CourseDirectory.Web/ViewComponents/LarsSearchResult/Default.cshtml
src/Dfc.CourseDirectory.Web/ViewModels/AddCourseDetailsViewModel.cs
src/Dfc.CourseDirectory.Web/ViewModels/AddCourseViewModel.cs
src/Dfc.CourseDirectory.Web/Views/AddCourse/AddCourse.cshtml
src/Dfc.CourseDirectory.Web/Views/AddCourse/AddCourseRun.cshtml
src/Dfc.CourseDirectory.Web/Views/AddCourse/Summary.cshtml

Navigation between AddCourse page1/page2 and Summary screen

Dfc 7316 change add course view

---

src/Dfc.CourseDirectory.Web/Views/Provider/Courses.cshtml

Need proper screen layout for this

Added provider no courses message & links

---

src/Dfc.CourseDirectory.Web/ViewComponents/Courses/CourseFor/Default.cshtml
src/Dfc.CourseDirectory.Web/Views/EditCourse/EditCourse.cshtml
src/Dfc.CourseDirectory.Web/wwwroot/dist/site.js
src/Dfc.CourseDirectory.Web/wwwroot/js/gds-jquery-ui.js

Making sure both char count and error message are being displayed in the error summary for edit course

Dfc 8070 bug screen1 not showing all errors in error summary

---

src/Dfc.CourseDirectory.Services/UnregulatedProvision/SectorSubjectAreaTier.cs
src/Dfc.CourseDirectory.Services/UnregulatedProvision/SectorSubjectAreaTier1.cs

DFC-8105 - data in prep for dropdowns

Unregulated provision

---

src/Dfc.CourseDirectory.Web/Views/EditCourse/EditCourse.cshtml
src/Dfc.CourseDirectory.Web/Views/EditCourseRun/EditCourseRun.cshtml
src/Dfc.CourseDirectory.Web/wwwroot/dist/site.js
src/Dfc.CourseDirectory.Web/wwwroot/js/gds-jquery-ui.js

DFC-8092, DFC-8097, DFC-8181, DFC-8135

Dfc 8092 select venue link error summary

---

src/Dfc.CourseDirectory.Models/Models/Venues/Venue.cs
src/Dfc.CourseDirectory.Services/VenueService/VenueService.cs
src/Dfc.CourseDirectory.Web/Controllers/AddCourseController.cs
src/Dfc.CourseDirectory.Web/Controllers/VenuesController.cs
src/Dfc.CourseDirectory.Web/ViewComponents/Courses/ChooseVenue/Default.cshtml
src/Dfc.CourseDirectory.Web/ViewComponents/Courses/SelectVenue/Default.cshtml
src/Dfc.CourseDirectory.Web/Views/AddCourse/AddCourseRun.cshtml
src/Dfc.CourseDirectory.Web/Views/ProviderCourses/Index.cshtml
src/Dfc.CourseDirectory.Web/Views/Venues/AddVenue.cshtml

Cour 455 missing venues

---

Resources/AzureSearch/SearchDatasource.json
Resources/AzureSearch/SearchIndex.json
Resources/AzureSearch/SearchIndexer.json

Added datasource, index and indexer for onspd (postcode)

NCSD-719: Added azure search

---

src/Dfc.CourseDirectory.Web/ViewComponents/PublishCourses/Publish/Default.cshtml

Modified text to include number of documents with issues and added links as per the prototype.

Modified text as per the prototype.

---

Resources/parameters.json
Resources/template.json

Added DfE signin variables:
* DFESignInSettings__Issuer
* DFESignInSettings__Audience
* DFESignInSettings__APISecret
* DFESignInSettings__ApiUri

NCSD-989: App settings v2.0

---

src/Dfc.CourseDirectory.Common/Dfc.CourseDirectory.Common.csproj
src/Dfc.CourseDirectory.Common/LoggerExtensions.cs
src/Dfc.CourseDirectory.Models/Dfc.CourseDirectory.Models.csproj
src/Dfc.CourseDirectory.Services/ApprenticeshipService/ApprenticeshipService.cs
src/Dfc.CourseDirectory.Services/CourseService/CourseService.cs
src/Dfc.CourseDirectory.Services/CourseTextService/CourseTextService.cs
src/Dfc.CourseDirectory.Services/Dfc.CourseDirectory.Services.csproj
src/Dfc.CourseDirectory.Services/ProviderService/ProviderService.cs
src/Dfc.CourseDirectory.Services/VenueService/VenueService.cs
src/Dfc.CourseDirectory.Web/Dfc.CourseDirectory.Web.csproj
tests/Dfc.CourseDirectory.Common.Tests/Dfc.CourseDirectory.Common.Tests.csproj
tests/Dfc.CourseDirectory.Models.Test/Dfc.CourseDirectory.Models.Test.csproj
tests/Dfc.CourseDirectory.Services.Tests/Dfc.CourseDirectory.Services.Tests.csproj
tests/Dfc.CourseDirectory.Web.Tests/Dfc.CourseDirectory.Web.Tests.csproj

Reverts SkillsFundingAgency/dfc-coursedirectory#754

Revert "COUR-1230 API-M changes into master"

---

src/Dfc.CourseDirectory.Common/Dfc.CourseDirectory.Common.csproj
src/Dfc.CourseDirectory.Models/Dfc.CourseDirectory.Models.csproj
src/Dfc.CourseDirectory.Services/Dfc.CourseDirectory.Services.csproj
src/Dfc.CourseDirectory.Web/Controllers/HomeController.cs
src/Dfc.CourseDirectory.Web/Dfc.CourseDirectory.Web.csproj
tests/Dfc.CourseDirectory.Models.Test/Dfc.CourseDirectory.Models.Test.csproj

COUR-1437 Fixes are: 1. When a Provider Super User signs in → Provider Dashboard. 2.When a Provider Super User signs in we no longer go the the “/Home/Check“ url either. 3. When a Helpdesk User signs in → Provider Search

COUR-1437 admin and helpdesk users redirect home page

---

src/Dfc.CourseDirectory.Models/Models/Courses/CsvDfcMigrationReport.cs
src/Dfc.CourseDirectory.Models/Models/Courses/DfcMigrationReport.cs
src/Dfc.CourseDirectory.Services/CourseService/CourseService.cs
src/Dfc.CourseDirectory.Services/Interfaces/CourseService/ICourseService.cs
src/Dfc.CourseDirectory.Web/Controllers/ReportController.cs

You'll notice the csv creation is in the controller. Once the font end page is ready i'll refactor this into a proper service

cour-1446 added migration report endpoint

---

src/Dfc.CourseDirectory.Web/ViewComponents/LarsSearchResult/Default.cshtml
src/Dfc.CourseDirectory.Web/ViewComponents/VenueName/Default.cshtml
src/Dfc.CourseDirectory.Web/Views/BulkUpload/Index.cshtml
src/Dfc.CourseDirectory.Web/Views/CourseSummary/Index.cshtml
src/Dfc.CourseDirectory.Web/Views/Home/Index.cshtml
src/Dfc.CourseDirectory.Web/Views/Shared/_GovukHeaderPartial_Your_Courses.cshtml
src/Dfc.CourseDirectory.Web/Views/Shared/_Layout_Your_Courses.cshtml

Cour 566 accessibility

---

src/Dfc.CourseDirectory.Common/StringExtensions.cs
src/Dfc.CourseDirectory.Services/BulkUploadService/ApprenticeshipBulkUploadService.cs
src/Dfc.CourseDirectory.Services/Interfaces/BulkUploadService/IApprenticeshipBulkUploadService.cs
src/Dfc.CourseDirectory.Services/LarsSearchFilterBuilder.cs
tests/Dfc.CourseDirectory.Common.Tests/Dfc.CourseDirectory.Common.Tests.csproj
tests/Dfc.CourseDirectory.Common.Tests/StringExtensionsTests.cs
tests/Dfc.CourseDirectory.Services.Tests/Dfc.CourseDirectory.Services.Tests.csproj
tests/Dfc.CourseDirectory.Services.Tests/Unit/ApprenticeshipBulkUploadServiceTests.cs
tests/Dfc.CourseDirectory.Services.Tests/Unit/Helpers/CsvStreams.cs

Starting to look at validating an apprenticeship CSV file.

Cour 1018 spike

---

src/Dfc.CourseDirectory.Models/Models/Courses/CsvDfcMigrationReport.cs
src/Dfc.CourseDirectory.Web/Controllers/ReportController.cs
src/Dfc.CourseDirectory.Web/ViewComponents/MigrationReportResults/Default.cshtml

Reverts SkillsFundingAgency/dfc-coursedirectory#959

Revert "Cour 1879"

---

src/Dfc.CourseDirectory.Models/Models/Courses/CsvDfcMigrationReport.cs
src/Dfc.CourseDirectory.Web/Controllers/ReportController.cs
src/Dfc.CourseDirectory.Web/ViewComponents/MigrationReportResults/Default.cshtml

Reverts SkillsFundingAgency/dfc-coursedirectory#961

Revert "Revert "Cour 1879""

---

src/Dfc.CourseDirectory.Web/Views/Venues/EditVenueName.cshtml

Replace 'venue' with 'location'

Fix content

---

src/Dfc.CourseDirectory.Web/Controllers/HomeController.cs

Whitelist a few actions for deactivated providers that don't require auth

---

src/Dfc.CourseDirectory.Web/Views/EditCourseRun/EditCourseRun.cshtml

Remove clearing Start Date

---

src/Dfc.CourseDirectory.WebV2/Features/ApprenticeshipQA/ApprenticeshipAssessment.cs
src/Dfc.CourseDirectory.WebV2/Features/ApprenticeshipQA/ApprenticeshipAssessment.cshtml
src/Dfc.CourseDirectory.WebV2/Features/ApprenticeshipQA/ProviderAssessment.cs
src/Dfc.CourseDirectory.WebV2/Features/ApprenticeshipQA/ProviderAssessment.cshtml
tests/Dfc.CourseDirectory.WebV2.Tests/Features/ApprenticeshipQA/ApprenticeshipAssessmentTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/Features/ApprenticeshipQA/ProviderAssessmentTests.cs

Require comments when assessment failed

---

src/Dfc.CourseDirectory.Web/Controllers/MigrationController.cs
src/Dfc.CourseDirectory.Web/ViewModels/Migration/DeleteCourseRunViewModel.cs
src/Dfc.CourseDirectory.Web/Views/Migration/CourseRunDeleted/Index.cshtml

- Changed screen that is navigated to after clicking delete.

Updated Delete Text.

---

src/Dfc.CourseDirectory.Web/Controllers/EditCourse/EditCourseRunController.cs
src/Dfc.CourseDirectory.Web/Controllers/PublishCourses/PublishCoursesController.cs
src/Dfc.CourseDirectory.Web/ViewComponents/PublishCourses/PublishCourse/Default.cshtml
src/Dfc.CourseDirectory.WebV2/Features/ApprenticeshipQA/ApprenticeshipQAController.cs
src/Dfc.CourseDirectory.WebV2/Features/ApprenticeshipQA/Complete.cs
src/Dfc.CourseDirectory.WebV2/Features/ApprenticeshipQA/Complete.cshtml
src/Dfc.CourseDirectory.WebV2/Features/ApprenticeshipQA/ProviderSelected.cshtml
tests/Dfc.CourseDirectory.WebV2.Tests/Features/ApprenticeshipQA/CompleteTests.cs

Ensure that IsValid status is used throughout the error fix screens and display errors based on that

bug fix for COUR-2396

---

src/Dfc.CourseDirectory.Web/Controllers/PublishCourses/PublishCoursesController.cs

https://skillsfundingagency.atlassian.net/browse/COUR-2437

fix for bug

---

src/Dfc.CourseDirectory.WebV2/Content/pttcd.css
src/Dfc.CourseDirectory.WebV2/DataStore/Sql/Queries/CreateApprenticeshipQAUnableToCompleteInfo.cs
src/Dfc.CourseDirectory.WebV2/DataStore/Sql/QueryHandlers/CreateApprenticeshipQAUnableToCompleteInfoHandler.cs
src/Dfc.CourseDirectory.WebV2/Features/ApprenticeshipQA/Status.cs
src/Dfc.CourseDirectory.WebV2/Features/ApprenticeshipQA/Status.cshtml
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/ApprenticeshipQA/StatusTests.cs

- Link Comments to 'Other' reason.
- Add StandardName when 'Standard not ready' chosen.
- Fixed up the styling.

Update Unable to Complete

---

src/Dfc.CourseDirectory.WebV2/Content/pttcd.css
src/Dfc.CourseDirectory.WebV2/Features/NewApprenticeshipProvider/ProviderDetailConfirmation.cshtml
src/Dfc.CourseDirectory.WebV2/Features/NewApprenticeshipProvider/ProviderDetailInfoPanel.cs
src/Dfc.CourseDirectory.WebV2/Features/NewApprenticeshipProvider/ProviderDetailInfoPanel.cshtml
src/Dfc.CourseDirectory.WebV2/Features/NewApprenticeshipProvider/ProviderDetailInfoPanelViewComponent.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/NewApprenticeshipProvider/ProviderDetailInfoPanel.cshtml
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/NewApprenticeshipProvider/ProviderDetailInfoPanelTests.cs

-- created panel
-- created unit test
-- updated CSS to match GDS

Added ProviderDetailInfoPanel component to ProviderDetailConfirmation page

---

src/Dfc.CourseDirectory.WebV2/Content/utilities/width.css
src/Dfc.CourseDirectory.WebV2/Features/ApprenticeshipQA/ListProviders.cshtml

Use inline style attribute for declaring width.

Fix column headers

---

src/Dfc.CourseDirectory.WebV2/MultiPageTransaction/LocalFileMptxStateProvider.cs

When FlowModel classes are changed during dev persisted instances may
fail to deserialize. Furthermore, since the entire DB file was
deserialized at once this makes the entire file unusable and requires
deleting it by hand.
This change makes deserialization more tolerant of failures. If an entry
cannot be deserialized it will be removed but other instances will be
unaffected.

Be more tolerant of FlowModel class changes for local dev

---

src/Dfc.CourseDirectory.WebV2/MultiPageTransaction/SessionMptxStateProvider.cs

Now we're using a distributed session store there's a chance a FlowModel
class could change before an instance is completed (e.g. a deployment
has happened) so it could fail to deserialize. Handle that case by
invalidating the instance.

Handle FlowModel deserialization errors

---

src/Dfc.CourseDirectory.Web/wwwroot/v2
src/Dfc.CourseDirectory.WebV2/DataStore/Sql/QueryHandlers/GetQAStatusReportHandler.cs
src/Dfc.CourseDirectory.WebV2/Features/ApprenticeshipQA/Report.cs
tests/Dfc.CourseDirectory.WebV2.Tests/CsvHelperExtensions.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/ApprenticeshipQA/QAStatusReportTests.cs

- Changed Report Headers using csvhelper attributes
- Added support for returning more than one unable to complete reason.
- Updated Tests.

QA Report bugs

---

src/Dfc.CourseDirectory.Web/Views/Home/Help.cshtml
src/Dfc.CourseDirectory.Web/Views/Home/Index.cshtml
src/Dfc.CourseDirectory.Web/Views/Provider/Landing.cshtml

change email address.

---

src/Dfc.CourseDirectory.WebV2/DataStore/CosmosDb/QueryHandlers/CreateApprenticeshipHandler.cs

Create apprenticeship handler

---

src/Dfc.CourseDirectory.WebV2/Features/ApprenticeshipQA/Report.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/ApprenticeshipQA/QAStatusReportTests.cs

- Removed ProviderId and QAStatus from report.
- Changed order of fields.
- Updated tests to remove checking for providerId & QaStatus.

removed providerId and qastatus fields from report.

---

src/Dfc.CourseDirectory.WebV2/DataStore/Sql/QueryHandlers/GetQAStatusReportHandler.cs

- Changed handler to support getting the latest Assessment.

Remove duplicate assessments

---

src/Dfc.CourseDirectory.WebV2/SharedViews/Components/AdminProviderContextNav.cshtml
src/Dfc.CourseDirectory.WebV2/SharedViews/Components/ProviderTopNav.cshtml
tests/Dfc.CourseDirectory.WebV2.Tests/LayoutTests.cs

- Ensure 'Your courses' is available where appropriate
- Fix 'Bulk upload' links in a few places

Fix up nav links

---

src/Dfc.CourseDirectory.WebV2/Helpers/Interfaces/IUkrlpSyncHelper.cs
src/Dfc.CourseDirectory.WebV2/Helpers/UkrlpSyncHelper.cs
src/Dfc.CourseDirectory.WebV2/Security/DfeUserInfoHelper.cs
tests/Dfc.CourseDirectory.WebV2.Tests/Helpers/UkrlpSyncHelperTests.cs

https://skillsfundingagency.atlassian.net/browse/PTCD-294

Fix for broken login

---

Resources/Azure/ArmTemplates/template.json

NCSD 3507 new function app

---

src/Dfc.CourseDirectory.Web/Controllers/UnregulatedCoursesController.cs
src/Dfc.CourseDirectory.Web/ViewComponents/ZCodeSearchResult/Default.cshtml
src/Dfc.CourseDirectory.Web/ViewComponents/ZCodeSearchResult/ZCodeSearchResultModel.cs
src/Dfc.CourseDirectory.Web/Views/UnRegulatedCourses/UnknownZCode.cshtml

Implementation of new pager view component on qualificaiton search page using javascript to jump between pages.

Implementing pager view component to the qualification search page

---

Resources/Azure/ArmTemplates/template.json

removed app setting from web app and added it to function app

NCSD-3623-updated function app settings

---

src/Dfc.CourseDirectory.Web/Controllers/VenuesController.cs
src/Dfc.CourseDirectory.Web/ViewComponents/VenueSearchResult/Default.cshtml

PTCD-164 #changed errror message.
- changed error message text when trying to delete a location associated with a live apprenticeship.
- Look at location guid too.

PTCD-164 #changed errror message.

---

src/Dfc.CourseDirectory.Web/ViewComponents/VenueSearchResult/Default.cshtml

ptcd-164 #amend course text

---

src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/UpsertLarsLearningDeliveries.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/UpsertHelper.cs

Also use SqlBulkCopy for greater perf

Fix importing DateTime columns in LARS records (PTCD-356)

---

src/Dfc.CourseDirectory.Web/Controllers/VenuesController.cs
src/Dfc.CourseDirectory.Web/Views/Venues/VenueAddressManualConfirmation.cshtml
src/Dfc.CourseDirectory.Web/Views/Venues/VenueAddressSelectionConfirmation.cshtml

ptcd-125 #add manual address country lookup warning.
- Updated manual address journey to lookup country by postcode, and display a warning if country is not england.

ptcd-125 #add manual address country lookup warning.

---

src/Dfc.CourseDirectory.Web/Controllers/UnregulatedCoursesController.cs

Display all 10 items added in ZCoreResults

Fix-Display All items (10 items per page) (PTCD-296)

---

.tool-versions

To allow easy install of dotnet sdk with https://asdf-vm.com/

Add .tool-versions

---

src/Dfc.CourseDirectory.Web/Controllers/VenuesController.cs

- Alter action to query ons for country so that none english postcode warning is not displayed by default.

PTCD-543 #Query ons for country to display non english postcode banner

---

src/Dfc.CourseDirectory.Web/ViewComponents/CourseName/Default.cshtml
src/Dfc.CourseDirectory.Web/ViewComponents/Courses/CourseFor/Default.cshtml

- removed autofocus attribute.

PTCD-492 #Removed autofocus attribute.

---

src/Dfc.CourseDirectory.Web/Controllers/AddCourseController.cs
src/Dfc.CourseDirectory.Web/ViewComponents/Courses/CourseFor/Default.cshtml
src/Dfc.CourseDirectory.Web/ViewComponents/Courses/EntryRequirements/Default.cshtml
src/Dfc.CourseDirectory.Web/ViewComponents/Courses/HowAssessed/Default.cshtml
src/Dfc.CourseDirectory.Web/ViewComponents/Courses/HowYouWillLearn/Default.cshtml
src/Dfc.CourseDirectory.Web/ViewComponents/Courses/WhatWillLearn/Default.cshtml
src/Dfc.CourseDirectory.Web/ViewComponents/Courses/WhatYouNeed/Default.cshtml
src/Dfc.CourseDirectory.Web/ViewComponents/Courses/WhereNext/Default.cshtml
src/Dfc.CourseDirectory.Web/Views/AddCourse/AddCourse.cshtml

* Strip trailing whitespace.
* Using back-link tag helper from pttcd instead of nuget after talking to James.
* The page H1 in the jira ticket overrules the one in the docx attached to the ticket.
* All copy changes are from the Jira ticket.
Note the previous page loses state when going back to it with the back link but that's beyond the scope of this ticket.

PTCD-414 - Updated design and text for Add Course page

---

src/Dfc.CourseDirectory.Web/Views/AddCourse/Summary.cshtml

As per prototype and jira ticket.
Note there's now a mismatch in names for "pattern" and "time" to be dealt with later. Checked with James and he said I would keep it as-is until we can change the model property everywhere
Diff best viewed without whitespace changes due to indentation change.

PTCD-418 Updated copy and design for publish course summary page

---

src/Dfc.CourseDirectory.Web/Views/AddCourse/AddCourse.cshtml

To match the Design System examples.

PTCD-414 Move "add course details" back-link out of main

---

Dfc.CourseDirectory.sln
Directory.Build.props
src/Dfc.CourseDirectory.Web/Dfc.CourseDirectory.Web.csproj
src/Dfc.CourseDirectory.Web/Views/AddCourse/AddCourse.cshtml
src/Dfc.CourseDirectory.Web/Views/AddCourse/AddCourseRun.cshtml
src/Dfc.CourseDirectory.Web/Views/Shared/LayoutModel.cs
src/Dfc.CourseDirectory.Web/Views/Shared/LayoutModelViedDataExtensions.cs
src/Dfc.CourseDirectory.Web/Views/Shared/_Layout_Your_Courses.cshtml
tests/Dfc.CourseDirectory.Web.Tests/Dfc.CourseDirectory.Web.Tests.csproj
tests/Dfc.CourseDirectory.Web.Tests/LayoutModelStorageTests.cs

* DRY markup for back links by moving it into the layout and making it togglable
* Introduce a layout for strong typing
* Introduce extension method for clean syntax for storing layout model
* Introduce new test project for Web(v1) to use as we work on the existing code
Used IDictionary rather than ViewDataDictionary for testability.

PTCD-410 - Refactor - Move back link to toggleable layout option

---

src/Dfc.CourseDirectory.Web/Views/AddCourse/AddCourseRun.cshtml

PTCD-410 - Update course details subtitle

---

src/Dfc.CourseDirectory.Web/Views/AddCourse/Summary.cshtml

PTCD-418 Course summary heading size

---

src/Dfc.CourseDirectory.Web/Controllers/VenuesController.cs

- Editing venue name caused non england address warning dialog to be shown. This change queries ons for country code, similar for other parts of the edit/add venue journey. Bug fix is for PTCD-543.

PTCD-570 #add ons postcode lookup for country code. PTCD-543 bugfix

---

Resources/AzureDevops/azure-pipelines.yml
src/Dfc.CourseDirectory.Web/Controllers/VenuesController.cs

- hotfix to fix postcode lookup warning.

PTCD-543 #fix postcode lookup for non english addresses.

---

src/Dfc.CourseDirectory.Web/Views/AddCourse/AddCourseDetails.cshtml

PTCD-410 Update add-course radio button hint text to "select"

---

tests/Dfc.CourseDirectory.Web.Tests/Controllers/BulkUploadApprenticeshipsControllerIntegrationTests.cs

Added a controller/service happy-path integration test for reliability during refactoring.

Added BulkUploadApprenticeship controller/service integration test

---

src/Dfc.CourseDirectory.Web/Views/BulkUploadApprenticeships/Index.cshtml

Updated BulkUploadApprenticeships view to include new layout and copy.
Design updated:
Further designs updates (22/07/2020):

Update Content + Layout on Apprenticeship Bulk Upload Page (PTCD 539)

---

src/Dfc.CourseDirectory.Core/BackgroundWorkers/IBackgroundWorkScheduler.cs
src/Dfc.CourseDirectory.Core/BackgroundWorkers/QueueBackgroundWorkScheduler.cs
src/Dfc.CourseDirectory.Core/BackgroundWorkers/WorkItem.cs
tests/Dfc.CourseDirectory.Core.Tests/BackgroundWorkersTests/QueueBackgroundWorkSchedulerTests.cs
tests/Dfc.CourseDirectory.Testing/ExecuteImmediatelyBackgroundWorkScheduler.cs

Usage:
```C#
IBackgroundWorkScheduler scheduler;
await scheduler.Schedule(RunMyBackgroundWork, state: new MyState());
static Task RunMyBackgroundWork(object state, IServiceProvider serviceProvider, CancellationToken cancellationToken)
{
MyState stronglyTypedState = (MyState)state;
var dep = serviceProvider.GetRequiredService<ISomeDependency>();
await dep.DoTheThing(state.Foo);
}
```

Add mechanism for executing work in the background

---

src/Dfc.CourseDirectory.Web/Views/AddCourse/AddCourseDetails.cshtml

To match prototype: https://dfc-providerportal-prototypes.herokuapp.com/sprint-2/course-run-details
https://skillsfundingagency.atlassian.net/browse/PTCD-410

[PTCD-410] Update cost of course hint

---

src/Dfc.CourseDirectory.Web/Views/BulkUpload/Index.cshtml

Updated BulkUpload view to match design and content specified in sprint 6 prototype

PTCD-538 Fix BulkUpload Page Design and Content

---

src/Dfc.CourseDirectory.Database/Pttcd/Tables/CourseRuns.sql

We have some bad data that cannot be synced with this constraint in
place. Fixing the data is out of scope for this change.

Remove foreign key

---

src/Dfc.CourseDirectory.Web/ViewComponents/Summary/SummaryComponent/Default.cshtml
src/Dfc.CourseDirectory.Web/ViewComponents/Summary/SummaryList/Default.cshtml

Updated SummaryComponent "change" link to capitalise "Change" and added visually hidden field name.

PTCD-614 FE Courses Update - Update Check and publish your course page Change link

---

src/Dfc.CourseDirectory.Web/Views/AddCourse/AddCourse.cshtml
src/Dfc.CourseDirectory.Web/Views/AddCourse/AddCourseDetails.cshtml

Changed the display text of submit button to always show "Continue" instead "Summary" when the last page vistited was the summary or the summary page has been visited.

PTCD-615 Change Summary Button to Continue

---

src/Dfc.CourseDirectory.Services/CourseService/CourseService.cs
src/Dfc.CourseDirectory.Web/Controllers/CourseSummaryController.cs
src/Dfc.CourseDirectory.Web/ViewComponents/Courses/ChooseRegion/Default.cshtml
src/Dfc.CourseDirectory.Web/Views/AddCourse/AddCourseDetails.cshtml

Updated AddCourseDetails "Work Based" copy
Disabled AddCourseDetails back button
Updated ChooseRegion component to use govuk-accordion for sub-region selection

PTCD-413 Course Details Page Work Based Content Updates

---

src/Dfc.CourseDirectory.Models/Models/Regions/SelectRegionModel.cs

Fixed Portsmouth region post code
Fixed duplicate SubRegionItemModel ApiLocationIds

PTCD-510 Region Data Fixes

---

src/Dfc.CourseDirectory.Web/Views/AddCourse/Summary.cshtml

Removed back button from AddCourse Summary page

PTCD-492 Removed back button from AddCourse Summary page

---

src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/Queries/GetProviderUkprnForApprenticeship.cs

Duplicates `src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/Queries/GetProviderUKPRNForApprenticeship.cs`

Delete duplicate file

---

src/Dfc.CourseDirectory.Web/Controllers/AddCourseController.cs
src/Dfc.CourseDirectory.Web/ViewModels/PublishedCourseViewModel.cs
src/Dfc.CourseDirectory.Web/Views/AddCourse/Published.cshtml

Added Published confirmation page to AddCourse

PTCD-419 Added Published confirmation page to AddCourse

---

src/Dfc.CourseDirectory.Web/Views/CourseSummary/Index.cshtml
src/Dfc.CourseDirectory.Web/Views/Shared/LayoutModel.cs
src/Dfc.CourseDirectory.Web/Views/Shared/_Layout_Your_Courses.cshtml
src/Dfc.CourseDirectory.WebV2/TagHelpers/BackLinkTagHelper.cs

Updated CourseSummary index view layout
Updated BackLinkTagHelper and LayoutModel to include customisable href and text + added custom backlink to CourseSummary page.

PTCD-423 Edit Course Information Page Updates

---

src/Dfc.CourseDirectory.Web/ViewComponents/Courses/ChooseRegion/Default.cshtml

Fixed ChooseRegion component form post with superfluous data from select all checkbox

Fix ChooseRegions Component Form Data

---

src/Dfc.CourseDirectory.Web/ViewComponents/Courses/ChooseVenue/Default.cshtml
src/Dfc.CourseDirectory.Web/Views/CopyCourseRun/CopyCourseRun.cshtml

Updated CopyCourseRun page design

PTCD-424 Updated CopyCourseRun page design

---

src/Dfc.CourseDirectory.Web/FileDistributedCache.cs
src/Dfc.CourseDirectory.Web/Startup.cs

Added FileDistributedCache and configured for development use only to persist state across builds

PTCD-493 Add FileDistributedCache For Development

---

src/Dfc.CourseDirectory.Web/FileDistributedCache.cs

Updated FileDistributedCache to clean out expired values and truncate file on write

PTCD-493 FileDistributedCache Fixes

---

src/Dfc.CourseDirectory.Web/Controllers/EditCourse/EditCourseController.cs
src/Dfc.CourseDirectory.Web/Controllers/EditCourse/EditCourseRunController.cs
src/Dfc.CourseDirectory.Web/ViewComponents/Courses/CourseFor/Default.cshtml
src/Dfc.CourseDirectory.Web/ViewComponents/Courses/DeliveryType/Default.cshtml
src/Dfc.CourseDirectory.Web/ViewComponents/Courses/EntryRequirements/Default.cshtml
src/Dfc.CourseDirectory.Web/ViewComponents/Courses/HowAssessed/Default.cshtml
src/Dfc.CourseDirectory.Web/ViewComponents/Courses/HowYouWillLearn/Default.cshtml
src/Dfc.CourseDirectory.Web/ViewComponents/Courses/WhatWillLearn/Default.cshtml
src/Dfc.CourseDirectory.Web/ViewComponents/Courses/WhatYouNeed/Default.cshtml
src/Dfc.CourseDirectory.Web/ViewComponents/Courses/WhereNext/Default.cshtml
src/Dfc.CourseDirectory.Web/Views/CourseSummary/Index.cshtml
src/Dfc.CourseDirectory.Web/Views/EditCourse/EditCourse.cshtml
src/Dfc.CourseDirectory.Web/Views/EditCourseRun/EditCourseRun.cshtml
src/Dfc.CourseDirectory.WebV2/Behaviors/TempDataKeys.cs
src/Dfc.CourseDirectory.WebV2/Content/components/notification.css
src/Dfc.CourseDirectory.WebV2/TagHelpers/NotificationTagHelper.cs
src/Dfc.CourseDirectory.WebV2/TempDataKeys.cs

Updated NotificationTagHelper to add Success variant and remove heading margin when content is empty
Updated EditCourseRun page and journey
Updated EditCourse page and journey

PTCD-650 Update Edit Course Journey

---

tests/Dfc.CourseDirectory.Core.Tests/Dfc.CourseDirectory.Core.Tests.csproj
tests/Dfc.CourseDirectory.Testing/ConfigurationBuilderExtensions.cs
tests/Dfc.CourseDirectory.Testing/Dfc.CourseDirectory.Testing.csproj

LocalDb is not cross platform so the connection strings have to be changed on linux.
https://stackoverflow.com/questions/45860851/localdb-is-not-supported-on-this-platform

Add user secrets config to test projects

---

src/Dfc.CourseDirectory.Web/Controllers/CopyCourse/CopyCourseRunController.cs
src/Dfc.CourseDirectory.Web/ViewModels/CopyCourse/CopyCourseRunSaveViewModel.cs
src/Dfc.CourseDirectory.Web/ViewModels/CopyCourse/CopyCourseRunSummaryViewModel.cs
src/Dfc.CourseDirectory.Web/ViewModels/CopyCourse/CopyCourseRunViewModel.cs
src/Dfc.CourseDirectory.Web/Views/CopyCourseRun/CopyCourseRun.cshtml
src/Dfc.CourseDirectory.Web/Views/CopyCourseRun/Published.cshtml
src/Dfc.CourseDirectory.Web/Views/CopyCourseRun/Summary.cshtml

Add Check and Publish and Published pages to CopyCourseRun journey

PTCD-493 Update Copy CourseRun Journey

---

Resources/AzureDevops/azure-pipelines.yml

Reduces the CI build time to ~4 minutes (from ~8 minutes)

CI build optimisations

---

src/Dfc.CourseDirectory.Web/ViewComponents/Courses/AddStartDate/Default.cshtml

Fixed Course StartDate hint padding

PTCD-669 Fixed Course StartDate hint padding

---

src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/GetExclusiveLock.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/GetExclusiveLockHandler.cs
src/Dfc.CourseDirectory.Core/SqlDataSync.cs
tests/Dfc.CourseDirectory.Core.Tests/SqlDataSyncTests.cs
tests/Dfc.CourseDirectory.Testing/DatabaseFixture.cs

Should fix PTCD-378 issues running in prod.

Prevent multiple instances of SyncAll* functions running concurrently

---

Dfc.CourseDirectory.sln

Update sln items list

---

src/Dfc.CourseDirectory.Web/ViewComponents/Courses/ChooseRegion/Default.cshtml
src/Dfc.CourseDirectory.WebV2/Content/pages/new-apprenticeship-provider/apprenticeship-employer-locations.js

Updated /new-apprenticeship-provider/apprenticeship-employer-locations-regions to include areas selected summary and changed "All" checkbox label to "Select all".

PTCD-644 Update QA Journey Regions Select Accordion

---

src/Dfc.CourseDirectory.Web/Controllers/BulkUploadController.cs
src/Dfc.CourseDirectory.Web/Views/BulkUpload/Upload.cshtml
src/Dfc.CourseDirectory.WebV2/Content/components/related-content.css
src/Dfc.CourseDirectory.WebV2/Content/utilities/table.css
src/Dfc.CourseDirectory.WebV2/Dfc.CourseDirectory.WebV2.csproj
src/Dfc.CourseDirectory.WebV2/Features/BulkUpload/BulkUploadController.cs
src/Dfc.CourseDirectory.WebV2/Features/BulkUpload/Courses.cshtml
src/Dfc.CourseDirectory.WebV2/Features/BulkUpload/CoursesFormatting.cshtml
src/Dfc.CourseDirectory.WebV2/Features/BulkUpload/Regions.cshtml
src/Dfc.CourseDirectory.WebV2/Features/BulkUpload/_ViewStart.cshtml

Added Courses-BulkUpload guidance to WebV2 features
Updated BulkUpload route to /bulk-upload/courses/upload and amended content + added legacy /BulkUpload route redirect

PTCD-639 FE Courses Bulk Upload Guidance

---

src/Dfc.CourseDirectory.Web/Controllers/BulkUploadApprenticeshipsController.cs
src/Dfc.CourseDirectory.Web/Views/BulkUploadApprenticeships/Upload.cshtml
src/Dfc.CourseDirectory.WebV2/Features/BulkUpload/Apprenticeships.cshtml
src/Dfc.CourseDirectory.WebV2/Features/BulkUpload/ApprenticeshipsFormatting.cshtml
src/Dfc.CourseDirectory.WebV2/Features/BulkUpload/BulkUploadController.cs
tests/Dfc.CourseDirectory.Web.Tests/Controllers/BulkUploadApprenticeshipsControllerIntegrationTests.cs
tests/Dfc.CourseDirectory.Web.Tests/Controllers/BulkUploadApprenticeshipsControllerTests.cs

Added Apprenticeships-BulkUpload guidance to WebV2 features
Updated BulkUploadApprenticeships route to /bulk-upload/apprenticeships/upload and amended content + added legacy /BulkUploadApprenticeships route redirect

PTCD-671 Apprenticeships Bulk Upload Guidance

---

src/Dfc.CourseDirectory.Web/Views/AddCourse/Summary.cshtml

Updated AddCourse Check and Publish page regions copy

PTCD-673 Update AddCourse Summary Regions Copy

---

README.md

Have a look at the [rich-text view in the PR](https://github.com/SkillsFundingAgency/dfc-coursedirectory/pull/1694/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
Please check this matches your understanding of how to get up and running.

Readme - Add developer/test setup

---

src/Dfc.CourseDirectory.WebV2/Dfc.CourseDirectory.WebV2.csproj
src/Dfc.CourseDirectory.WebV2/Features/ApprenticeshipQA/ApprenticeshipAssessment.cshtml
src/Dfc.CourseDirectory.WebV2/Features/ApprenticeshipQA/ProviderAssessment.cshtml
src/Dfc.CourseDirectory.WebV2/Features/ApprenticeshipQA/Status.cshtml
src/Dfc.CourseDirectory.WebV2/Features/Apprenticeships/ClassroomLocation.cshtml
src/Dfc.CourseDirectory.WebV2/Features/Apprenticeships/FindStandard.cshtml
src/Dfc.CourseDirectory.WebV2/Features/Cookies/Settings.cshtml
src/Dfc.CourseDirectory.WebV2/Features/DeleteCourseRun/View.cshtml
src/Dfc.CourseDirectory.WebV2/Features/EditVenue/Address.cshtml
src/Dfc.CourseDirectory.WebV2/Features/EditVenue/Email.cshtml
src/Dfc.CourseDirectory.WebV2/Features/EditVenue/Name.cshtml
src/Dfc.CourseDirectory.WebV2/Features/EditVenue/PhoneNumber.cshtml
src/Dfc.CourseDirectory.WebV2/Features/EditVenue/Website.cshtml
src/Dfc.CourseDirectory.WebV2/Features/NewApprenticeshipProvider/ApprenticeshipDetails.cshtml
src/Dfc.CourseDirectory.WebV2/Features/NewApprenticeshipProvider/ApprenticeshipEmployerLocations.cshtml
src/Dfc.CourseDirectory.WebV2/Features/NewApprenticeshipProvider/ApprenticeshipEmployerLocationsRegions.cshtml
src/Dfc.CourseDirectory.WebV2/Features/NewApprenticeshipProvider/ApprenticeshipLocations.cshtml
src/Dfc.CourseDirectory.WebV2/Features/NewApprenticeshipProvider/ProviderDetail.cshtml
src/Dfc.CourseDirectory.WebV2/Features/Providers/EditProviderInfo.cshtml

Simplify govuk-error-summary usage

---

README.md
src/Dfc.CourseDirectory.WebV2/README.md

Readme - add some code architecture info
To provide an agreed path, a reminder for the existing team, a reference for code-review, and an easier onboarding for future contributors.
* Use the rich-diff button on the files-changed tab to see formatting and check links.
* This was a quick brain-dump, please contribute corrections etc but let's get something quick in and then iterate with more PRs once this is in.

Readme - add some code architecture info

---

src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/Queries/GetApprenticeships.cs
src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/Queries/GetApprenticeshipsByIds.cs
src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/QueryHandlers/GetApprenticeshipsHandler.cs
src/Dfc.CourseDirectory.Functions/ArchiveApprenticeships.cs
src/Dfc.CourseDirectory.Functions/GetAllFrameworkApprenticeshipIds.cs
src/Dfc.CourseDirectory.Functions/GetAllPublishedFrameworkApprenticeshipIds.cs
src/Dfc.CourseDirectory.Web/Controllers/ApprenticeshipsController.cs
tests/Dfc.CourseDirectory.Testing/TestData/TestData.CreateApprenticeshipQASubmission.cs

Updated ApprenticeshipsController.ViewAndEdit to show only found Apprenticeships with RecordStaus.Live
Added GetApprenticeships Cosmos query and GetAllFrameworkApprenticeshipIds Function
Added ArchiveApprenticeships Function

PTCD-696 Suppress Apprenticeship Frameworks

---

Resources/ArmTemplates/template.json
src/Dfc.CourseDirectory.Services/ApprenticeshipBulkUploadService/ApprenticeshipBulkUploadService.cs
src/Dfc.CourseDirectory.Services/BlobStorageService/BlobStorageService.cs
src/Dfc.CourseDirectory.Services/BlobStorageService/BlobStorageSettings.cs
src/Dfc.CourseDirectory.Services/BlobStorageService/IBlobStorageService.cs
src/Dfc.CourseDirectory.Services/Models/Apprenticeships/CsvApprenticeship.cs
src/Dfc.CourseDirectory.Web/Controllers/BlobStorageController.cs
src/Dfc.CourseDirectory.Web/Helpers/ApprenticeshipProvisionHelper.cs
src/Dfc.CourseDirectory.Web/Helpers/IApprenticeshipProvisionHelper.cs
src/Dfc.CourseDirectory.Web/appsettings.json
src/Dfc.CourseDirectory.WebV2/Features/BulkUpload/ApprenticeshipsFormatting.cshtml

Updated BlobStorageController GetApprenticeshipBulkUploadTemplateFile to generate template file on demand in code
Removed Frameworks from Apprenticeships Bulk Upload templates + updated ApprenticeshipsBulkUploadService to accept csv files without FRAMEWORK_CODE, FRAMEWORK_PROG_TYPE and FRAMEWORK_PATHWAY_CODE columns

PTCD-697 Remove Frameworks from Apprenticeships Bulk Upload

---

src/Dfc.CourseDirectory.Web/Controllers/PublishApprenticeships/PublishApprenticeshipsController.cs
src/Dfc.CourseDirectory.Web/Views/Apprenticeships/Details/Index.cshtml
src/Dfc.CourseDirectory.Web/Views/EditApprenticeship/EditApprenticeship.cshtml

Updated Apprenticeships journey telephone number entry validation to accept 10-digit telephone numbers

PTCD-652 Update Apprenticeships Telephone Number Validation

---

tests/Dfc.CourseDirectory.Testing/appsettings.Testing.json

Feature flag has already been removed

Remove old QA feature flag from settings file

---

src/Dfc.CourseDirectory.Core/Search/AzureSearch/AzureSearchClient.cs
src/Dfc.CourseDirectory.Core/Search/SearchResult.cs
src/Dfc.CourseDirectory.Core/Search/SearchResultItem.cs
src/Dfc.CourseDirectory.Services/BulkUploadService/BulkUploadService.cs
src/Dfc.CourseDirectory.Web/Controllers/LarsSearchController.cs
src/Dfc.CourseDirectory.Web/Controllers/MigrationController.cs
src/Dfc.CourseDirectory.Web/Controllers/SearchProvider/SearchProviderController.cs
src/Dfc.CourseDirectory.Web/Controllers/UnregulatedCoursesController.cs
src/Dfc.CourseDirectory.Web/Controllers/VenuesController.cs
src/Dfc.CourseDirectory.WebV2/Features/EditVenue/Address.cs
tests/Dfc.CourseDirectory.Core.Tests/Search/AzureSearch/AzureSearchClientTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/EditVenue/AddressTests.cs

FAC API needs the score to be available for each result.

Add score to search response

---

README.md
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/GetProviderApprenticeshipQAStatusHandler.cs

To make it easier to work on the apprenticeship features during local development.

Debug ability to bypass QA

---

src/Dfc.CourseDirectory.Functions/Startup.cs

It has transient dependencies and should be transient itself.

Fix lifetime of SqlDataSync

---

src/Dfc.CourseDirectory.Web/Helpers/ApprenticeshipProvisionHelper.cs

Fixed `ApprenticeshipProvisionHelper` `NullReferenceException` on `MapCsvApprenticeship`

Fix ApprenticeshipProvisionHelper NullReferenceException

---

src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/Models/Course.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/UpsertCoursesFromCosmos.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/UpsertCoursesFromCosmosHandler.cs
src/Dfc.CourseDirectory.Core/SqlDataSync.cs
src/Dfc.CourseDirectory.Database/Dfc.CourseDirectory.Database.sqlproj
src/Dfc.CourseDirectory.Database/Pttcd/Tables/CourseRunSubRegions.sql
tests/Dfc.CourseDirectory.Core.Tests/SqlDataSyncTests.cs

Turns out RegionIds doesn't contain sub-regions.

Sync CourseRun subregions to SQL

---

src/Dfc.CourseDirectory.Functions/DeleteDuplicateProviderRecords.cs

Also included a read-only 'dry run' function.

PTCD-763 Add Azure Function for removing duplicate provider records from Cosmos

---

src/Dfc.CourseDirectory.Core/DataStore/Sql/Models/TLevelDefinition.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/CreateTLevelDefinition.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/GetTLevelDefinitions.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/GetTLevelDefinitionsForProvider.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/UpsertProviderTLevelDefinitions.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/CreateTLevelDefinitionHandler.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/GetTLevelDefinitionsForProviderHandler.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/GetTLevelDefinitionsHandler.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/UpsertProviderTLevelDefinitionsHandler.cs
src/Dfc.CourseDirectory.Core/Models/ProviderType.cs
src/Dfc.CourseDirectory.Database/Dfc.CourseDirectory.Database.sqlproj
src/Dfc.CourseDirectory.Database/Pttcd/Tables/ProviderTLevelDefinitions.sql
src/Dfc.CourseDirectory.Database/Pttcd/Tables/TLevelDefinitions.sql
src/Dfc.CourseDirectory.Database/Scripts/Script.PostDeploy.sql
src/Dfc.CourseDirectory.WebV2/Features/Providers/EditProviderType.cs
src/Dfc.CourseDirectory.WebV2/Features/Providers/EditProviderType.cshtml
src/Dfc.CourseDirectory.WebV2/Features/Providers/EditProviderTypeController.cs
src/Dfc.CourseDirectory.WebV2/Features/Providers/ProviderDetails.cs
src/Dfc.CourseDirectory.WebV2/Features/Providers/ProviderDetails.cshtml
src/Dfc.CourseDirectory.WebV2/Features/Providers/ProviderTLevelDefinitionViewModel.cs
src/Dfc.CourseDirectory.WebV2/Features/Providers/TLevelDefinitionViewModel.cs
tests/Dfc.CourseDirectory.Testing/TestData/TestData.CreateTLevelDefinition.cs
tests/Dfc.CourseDirectory.Testing/TestData/TestData.SetProviderTLevelDefinition.cs
tests/Dfc.CourseDirectory.Testing/appsettings.Testing.json
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/Providers/EditProviderTypeTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/Providers/ProviderDetailsTests.cs

Added ProviderType.TLevels and updated EditProviderType to allow selection of TLevels ProviderType
Added TLevelDefinitions and ProviderTLevelDefinitions to SQL database
Added configure TLevelDefinitions for Provider functionality

PTCD-743 Grant Provider T Level Status

---

src/Dfc.CourseDirectory.Web/Controllers/LocationsController.cs

This was missed in f64ce0b311c9849cc1d7ef4cc9c49d81d16af39e

Sync changes to SQL when Venue is deleted

---

src/Dfc.CourseDirectory.Core/SqlDataSync.cs

Reduce the batch size and add a timeout between retries on Cosmos->SQL sync

Merge Kepler hotfixes to main

---

src/Dfc.CourseDirectory.Core/Models/VenueStatus.cs

Code doc - make VenueStatus pending doc into xmldoc
So that you can see it from usages.
---
update: now Obsolete is available from #1840 have switched to that

Mark VenueStatus pending as obsolete

---

src/Dfc.CourseDirectory.Core/Search/CourseSearchQuery.cs
src/Dfc.CourseDirectory.Core/Search/Models/FindACourseOffering.cs
src/Dfc.CourseDirectory.FindACourseApi/Controllers/CoursesController.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/CourseRunDetail/CourseRunDetail.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/CourseRunDetail/CourseRunDetailViewModel.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/Search/CoordinatesViewModel.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/Search/FacetCountResultViewModel.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/Search/Search.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/Search/SearchResultViewModel.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/Search/SearchSortBy.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/Search/SearchViewModel.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/TLevelDetail/ProviderViewModel.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/TLevelDetail/QualificationViewModel.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/TLevelDetail/Query.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/TLevelDetail/TLevelDetailViewModel.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/TLevelDetail/TLevelLocationViewModel.cs
src/Dfc.CourseDirectory.FindACourseApi/Startup.cs
tests/Dfc.CourseDirectory.FindACourseApi.Tests/FeatureTests/CourseSearchTests.cs
tests/Dfc.CourseDirectory.FindACourseApi.Tests/FindACourseApiApplicationFactory.cs
tests/Dfc.CourseDirectory.FindACourseApi.Tests/TestBase.cs

Add a stub response for the new TLevelDetail operation.

Update FAC API schema for T Levels

---

src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/GetProviderDashboardCounts.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/GetProviderDashboardCountsHandler.cs
src/Dfc.CourseDirectory.WebV2/Features/ProviderDashboard/Dashboard.cs
src/Dfc.CourseDirectory.WebV2/Features/ProviderDashboard/Dashboard.cshtml
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/ProviderDashboard/DashboardTests.cs

PTCD-729 Added T Levels Card to ProviderDashboard

---

src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/QueryHandlers/GetApprenticeshipsByIdsHandler.cs
src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/QueryHandlers/GetApprenticeshipsHandler.cs
tests/Dfc.CourseDirectory.Core.Tests/SqlDataSyncTests.cs
tests/Dfc.CourseDirectory.Testing/DataStore/CosmosDb/QueryHandlers/ArchiveApprenticeshipsForProviderHandler.cs
tests/Dfc.CourseDirectory.Testing/DataStore/CosmosDb/QueryHandlers/UpdateApprenticeshipHandler.cs

Refactor - use enums for apprenticeship RecordStatus values

---

src/Dfc.CourseDirectory.Core/Models/ProviderType.cs
src/Dfc.CourseDirectory.WebV2/Features/Providers/EditProviderType.cshtml
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/Providers/ProviderDetailsTests.cs

PTCD-733 Updated FE Provider Type Label

---

src/Dfc.CourseDirectory.Functions/local.settings.json

To avoid interruptions to local debugging when connected to shared dev CosmosDB

Disable RealTimeSyncCosmosUkrlpToSql for local development

---

src/Dfc.CourseDirectory.WebV2/Features/Providers/EditProviderType.cshtml

Fix Provider Type Settings Checkbox Labels

---

Dfc.CourseDirectory.FindAnApprenticeshipApi/Dfc.CourseDirectory.FindAnApprenticeshipApi.sln
tests/Dfc.CourseDirectory.FindAnApprenticeship.Tests/Helper/DasHelperTests.cs
tests/Dfc.CourseDirectory.FindAnApprenticeship.Tests/Helper/MockTelemetryHelper.cs
tests/Dfc.CourseDirectory.FindAnApprenticeship.Tests/Integration/GetApprenticeshipsAsProviderIntegrationTests.cs

Stopped tests blowing up on release builds with an App Insights telemetry mock

Stopped tests blowing up on release builds with an App Insights telemetry mock

---

.github/CODEOWNERS
Dfc.CourseDirectory.FindACourseApi/Resources/AzureDevops/azure-pipelines.yml
Dfc.CourseDirectory.FindAnApprenticeshipApi/Resources/ArmTemplates/parameters.json
Dfc.CourseDirectory.FindAnApprenticeshipApi/Resources/ArmTemplates/template.json
Dfc.CourseDirectory.FindAnApprenticeshipApi/Resources/ArmTemplates/test-parameters.json
Dfc.CourseDirectory.FindAnApprenticeshipApi/Resources/AzureDevOps/azure-pipelines.yml

Updated Application Insights for FindanApprenticeshipApi to consolidate with CD AI
Updated build pipeline for Agent pool definitions
Updated code owners with folder structure for DevOps resources folder

NCSD-4944 Consolidate pipelines

---

src/Dfc.CourseDirectory.Web/Controllers/VenuesController.cs
src/Dfc.CourseDirectory.Web/Views/Venues/EditVenueAddress.cshtml
src/Dfc.CourseDirectory.Web/Views/Venues/EditVenueName.cshtml

These were removed in 6634f4d74da5356dbb3dd4aed00ffc35b931b992 in error.
Resurrected the old code as-was with no changes; new journey is coming soon to replace it all.

Fix editing name & address when adding a venue

---

src/Dfc.CourseDirectory.WebV2/Features/TLevels/ViewTLevels/ViewTLevels.cshtml

Updated ViewTLevels to always show Add T Levels button

PTCD-805 View T Levels Add T Level Button Display

---

src/Dfc.CourseDirectory.Web/Controllers/EditCourse/EditCourseRunController.cs

Updated Edit FE Course to remove StartDate before pre-edited StartDate validation

PTCD-768 Edit FE Course StartDate Validation

---

src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/Queries/ProcessAllApprenticeships.cs
src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/Queries/UpdateApprenticeshipLocationDeliveryMode.cs
src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/QueryHandlers/ProcessAllApprenticeshipsHandler.cs
src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/QueryHandlers/UpdateApprenticeshipLocationDeliveryModeHandler.cs
src/Dfc.CourseDirectory.Functions/FixEmptyApprenticeshipLocationDeliveryModes.cs

Added FixEmptyApprenticeshipLocationDeliveryModes to Functions

PTCD-585 Fix Empty ApprenticeshipLocation DeliveryModes Function

---

src/Dfc.CourseDirectory.WebV2/Features/TLevels/AddTLevel/CheckAndPublish.cshtml
src/Dfc.CourseDirectory.WebV2/Features/TLevels/AddTLevel/Description.cshtml
src/Dfc.CourseDirectory.WebV2/Features/TLevels/AddTLevel/Published.cshtml

[PTCD-803](https://skillsfundingagency.atlassian.net/browse/PTCD-803)
Screenshots with changes applied:

[PTCD-803] Update content on T Levels "add" journey

---

src/Dfc.CourseDirectory.Core/ConfigurationFeatureFlagProvider.cs
src/Dfc.CourseDirectory.Core/FeatureFlagProviderExtensions.cs
src/Dfc.CourseDirectory.Core/FeatureFlags.cs
src/Dfc.CourseDirectory.Core/IFeatureFlagProvider.cs
src/Dfc.CourseDirectory.Web/appsettings.Environment.PreProduction.json
src/Dfc.CourseDirectory.WebV2/CanaryUserFeatureFlagProvider.cs
src/Dfc.CourseDirectory.WebV2/ServiceCollectionExtensions.cs
src/Dfc.CourseDirectory.WebV2/TLevelsBetaCanaryUserFeatureFlagProvider.cs
tests/Dfc.CourseDirectory.Testing/OverridableFeatureFlagProvider.cs

Added CanaryUserFeatureFlagProvider and configured TLevelsBeta flag with admin user to provide TLevels flag

PTCD 835 T Levels Canary Feature Flags

---

src/Dfc.CourseDirectory.WebV2/Features/TLevels/ViewAndEditTLevel/CheckAndPublish.cshtml

Follow up to #1899 - missed a bit.
[PTCD-803](https://skillsfundingagency.atlassian.net/browse/PTCD-803)
Screenshots with changes applied:

[PTCD-803] Update copytext on edit-tlevel page

---

src/Dfc.CourseDirectory.Web/Views/CopyCourseRun/CopyCourseRun.cshtml
src/Dfc.CourseDirectory.Web/Views/CopyCourseRun/Published.cshtml
src/Dfc.CourseDirectory.WebV2/Features/DeleteCourseRun/Confirmed.cshtml
src/Dfc.CourseDirectory.WebV2/Features/DeleteCourseRun/View.cshtml

* [PTCD-815](https://skillsfundingagency.atlassian.net/browse/PTCD-815) - Tidy up course deletion confirmation display
* [PTCD-814](https://skillsfundingagency.atlassian.net/browse/PTCD-814) - Tidy up copy-course "published" display
* [PTCD-812](https://skillsfundingagency.atlassian.net/browse/PTCD-812) - Space out buttons on copy-course
* [PTCD-809](https://skillsfundingagency.atlassian.net/browse/PTCD-809) - Space out delete-course buttons
Updated screens:

Course editing UI tweaks

---

src/Dfc.CourseDirectory.WebV2/Features/TLevels/ViewAndEditTLevel/Published.cshtml

[PTCD-845](https://skillsfundingagency.atlassian.net/browse/PTCD-845)
After:

[PTCD-845] Copytext for edited t-level page

---

src/Dfc.CourseDirectory.FindACourseApi/Controllers/CoursesController.cs
src/Dfc.CourseDirectory.FindACourseApi/Controllers/SearchController.cs
src/Dfc.CourseDirectory.FindACourseApi/Controllers/TLevelsController.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/TLevelDefinitions/TLevelDefinitionViewModel.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/TLevelDefinitions/TLevelDefinitions.cs
src/Dfc.CourseDirectory.FindACourseApi/appsettings.Testing.json
tests/Dfc.CourseDirectory.FindACourseApi.Tests/FeatureTests/TLevelDefinitionsTests.cs

[PTCD-838](https://skillsfundingagency.atlassian.net/browse/PTCD-838)

PTCD-838 Added TLevelDefinitions endpoint to FAC

---

src/Dfc.CourseDirectory.Core/Search/Models/Provider.cs

No references to these in the code.

Remove unused provider search fields

---

src/Dfc.CourseDirectory.Web/Controllers/AddCourseController.cs

[PTCD-563](https://skillsfundingagency.atlassian.net/browse/PTCD-563)
CreatedBy was blank because it seems DfE Sign-in had at some point changed from "email" to "Email".
After discussion with the team we are going to use UserId as it's stable and avoids any personal information.

[PTCD-563] Audit UserId when adding a course

---

src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/Queries/DeleteCourseRun.cs
src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/QueryHandlers/DeleteCourseRunHandler.cs
src/Dfc.CourseDirectory.WebV2/Features/DeleteCourseRun/DeleteCourseRun.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DeleteCourseRunTests.cs

[PTCD-466](https://skillsfundingagency.atlassian.net/browse/PTCD-466)
~Lack of tests bothers me on this, but I'm not sure how to add in useful testing given the cosmos stuff is all mocked with sql handlers for testing. Suggestions welcome.~

[PTCD-466] Populate updated* fields when deleting a course

---

src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/Queries/GetFeChoicesByProviderUkprns.cs
src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/QueryHandlers/GetFeChoicesByProviderUkprnsHandler.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/GetProvidersByIds.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/GetTLevels.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/GetProvidersByIdsHandler.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/GetTLevelsHandler.cs
src/Dfc.CourseDirectory.FindACourseApi/Controllers/TLevelsController.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/CourseRunDetail/CourseRunDetail.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/TLevels/ProviderViewModel.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/TLevels/QualificationViewModel.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/TLevels/TLevelDetail.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/TLevels/TLevelDetailViewModel.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/TLevels/TLevelLocationViewModel.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/TLevels/TLevels.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/ViewModelFormatting.cs
src/Dfc.CourseDirectory.FindACourseApi/Startup.cs
tests/Dfc.CourseDirectory.FindACourseApi.Tests/FeatureTests/TLevelDetailTests.cs
tests/Dfc.CourseDirectory.FindACourseApi.Tests/FeatureTests/TLevelsTests.cs

PTCD-837 Added TLevels Endpoint to FAC

---

src/Dfc.CourseDirectory.Web/appsettings.Environment.Production.json

Added TLevelsBeta feature flag to Prod config

Enable TLevelsBeta Feature Flag in Prod

---

src/Dfc.CourseDirectory.Database/Pttcd/Views/vwProviderSearchIndex.sql

Updated vwProviderSearchIndex to use ProviderContact Town if available

Provider Search Index Use ProviderContact Town

---

Dfc.CourseDirectory/Resources/ArmTemplates/parameters.json
Dfc.CourseDirectory/Resources/ArmTemplates/template.json
Dfc.CourseDirectory/Resources/ArmTemplates/test-parameters.json
src/Dfc.CourseDirectory.Web/appsettings.json
src/Dfc.CourseDirectory.WebV2/AddressSearch/GetAddressAddressSearchService.cs
src/Dfc.CourseDirectory.WebV2/AddressSearch/GetAddressAddressSearchServiceOptions.cs
src/Dfc.CourseDirectory.WebV2/ServiceCollectionExtensions.cs
tests/Dfc.CourseDirectory.WebV2.Tests/AddressSearch/GetAddressAddressSearchServiceTests.cs

Added GetAddress api config values into Arm Templates
Updated GetAddressSearchService to use configured ApiUrl
Updated IAddressSearchService registration to use GetAddressSearchService

PTCD-676 Replace LoqateAddressSearchService with GetAddressAddressSearchService

---

src/Dfc.CourseDirectory.Web/ViewComponents/Courses/Attendance/Default.cshtml

Fixed EditCourseRun AttendanceMode radios DayorBlockRelease label

PTCD-658 Fix EditCourseRun AttendanceMode Radios DayorBlockRelease Label

---

src/Dfc.CourseDirectory.Web/ViewComponents/ZCodeSearchResult/Default.cshtml

Fixed non-regulated course search pagination with filters

PTCD-759 Fix Non-Regulated Course Search Pagination With Filters

---

Dfc.CourseDirectory/Resources/AzureSearch/SearchDatasource.json
Dfc.CourseDirectory/Resources/AzureSearch/SearchIndex.json
Dfc.CourseDirectory/Resources/AzureSearch/SearchIndexer.json

Moved LARS search index definition from `dfc-providerportal-lars`

PTCD-865 Move LARS Search Index Definition From LARS Service to CD

---

src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/UpsertLarsStandardSectorCodes.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/UpsertLarsStandards.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/UpsertLarsStandardSectorCodesHandler.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/UpsertLarsStandardsHandler.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/UpsertHelper.cs
src/Dfc.CourseDirectory.Core/ReferenceData/Lars/LarsDataImporter.cs
src/Dfc.CourseDirectory.Database/Dfc.CourseDirectory.Database.sqlproj
src/Dfc.CourseDirectory.Database/Pttcd/Tables/StandardSectorCodes.sql
src/Dfc.CourseDirectory.Database/Pttcd/Tables/Standards.sql
tests/Dfc.CourseDirectory.Core.Tests/ReferenceDataTests/LarsDataImporterTests.cs

Added Standards table to SQL and updated LarsDataImporter to sync Standards to SQL
Added StandardSectorCodes table to SQL and updated LarsDataImporter to sync StandardSectorCodes to SQL

PTCD-843 Sync LARS Standards Data to SQL

---

src/Dfc.CourseDirectory.Core/DataManagement/IVenueUploadProcessor.cs
src/Dfc.CourseDirectory.Core/DataManagement/SaveFileResult.cs
src/Dfc.CourseDirectory.Core/DataManagement/VenueUploadProcessor.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/Models/VenueUpload.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/CreateVenueUpload.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/GetLatestIncompleteVenueUploadForProvider.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/GetVenueUpload.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/UpdateVenueUploadStatus.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/CreateVenueUploadHandler.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/GetLatestIncompleteVenueUploadForProviderHandler.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/GetVenueUploadHandler.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/UpdateVenueUploadStatusHandler.cs
src/Dfc.CourseDirectory.Core/Models/UploadStatus.cs
src/Dfc.CourseDirectory.Database/Dfc.CourseDirectory.Database.sqlproj
src/Dfc.CourseDirectory.Database/Pttcd/Tables/VenueUploads.sql
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Venues/Upload.cs
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Venues/Upload.cshtml
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Venues/VenuesDataManagementController.cs
src/Dfc.CourseDirectory.WebV2/ServiceCollectionExtensions.cs
tests/Dfc.CourseDirectory.Testing/TestData/TestData.CreateVenueUpload.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Venues/UploadTests.cs

Adds additional checks that venue files are valid & database schema.

PTCD-917 Venue Upload file checks

---

src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/GetProviderMissingPrimaryContactReport.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/GetProviderMissingPrimaryContactReportHandler.cs
src/Dfc.CourseDirectory.WebV2/Features/HelpdeskDashboard/Dashboard.cshtml
src/Dfc.CourseDirectory.WebV2/Features/Providers/Reporting/ProviderMissingPrimaryContactReport.cs
src/Dfc.CourseDirectory.WebV2/Features/Providers/Reporting/ProviderReportsController.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/HelpdeskDashboard/DashboardTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/Providers/Reporting/ProviderMissingPrimaryContactReportTests.cs

- Added sql required for generating csv report
- added unit tests to show providers with no contact details.

Ptcd-889 providers with no primary contact details

---

src/Dfc.CourseDirectory.WebV2/Features/ProviderDashboard/Dashboard.cshtml

Got on a call with Cathie and found out upload in progress checks are not for this ticket. They are for SDD-821

venue upload card links

---

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/Upload.cshtml

Missing bullet point

---

src/Dfc.CourseDirectory.Core/DataManagementFeatureFlagProvider.cs
src/Dfc.CourseDirectory.Core/FeatureFlags.cs
src/Dfc.CourseDirectory.Web/appsettings.Development.json
src/Dfc.CourseDirectory.Web/appsettings.Environment.Development.json
src/Dfc.CourseDirectory.Web/appsettings.Environment.SIT.json
src/Dfc.CourseDirectory.Web/appsettings.Environment.SIT2.json
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/CoursesDataManagementController.cs
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Dashboard.cshtml
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Venues/VenuesDataManagementController.cs
src/Dfc.CourseDirectory.WebV2/Features/ProviderDashboard/Dashboard.cshtml
src/Dfc.CourseDirectory.WebV2/ServiceCollectionExtensions.cs
tests/Dfc.CourseDirectory.Testing/appsettings.Testing.json
tests/Dfc.CourseDirectory.WebV2.Tests/Startup.cs

Compute a 'DataManagement' feature flag if any of VenuesDataManagement
or CoursesDataManagement are defined.

Split data management feature flags by entity

---

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Venues/DeleteUploadSuccess.cshtml
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Venues/VenuesDataManagementController.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Venues/DeleteUploadTests.cs

- added confirmation page for deleting a venue upload file.

SDD-847 - Delete Venues Upload confirmation.

---

src/Dfc.CourseDirectory.Database/Pttcd/StoredProcedures/RefreshFindACourseIndex.sql
src/Dfc.CourseDirectory.Database/Pttcd/StoredProcedures/RefreshFindACourseIndexForTLevels.sql
src/Dfc.CourseDirectory.Database/Pttcd/Tables/FindACourseIndex.sql
src/Dfc.CourseDirectory.Functions/UpdateFindACourseIndexVenueId.cs

Add a `VenueId` column to the `FindACourseIndex` table so we can directly update entries when venues are changed.

Optimise FAC index updates when venues are changed part 1

---

src/Dfc.CourseDirectory.WebV2/SharedViews/Components/AdminProviderContextNav.cshtml
src/Dfc.CourseDirectory.WebV2/SharedViews/Components/ProviderTopNav.cshtml
tests/Dfc.CourseDirectory.Testing/appsettings.Testing.json
tests/Dfc.CourseDirectory.WebV2.Tests/LayoutTests.cs

- Rename label to Data Upload
- Update tests

SDD-906 - rename label & tests

---

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/CoursesDataManagementController.cs
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/Formatting.cshtml
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/Upload.cshtml

- Added new View for formatting page.

SDD-886 - Course Guidance Page

---

src/Dfc.CourseDirectory.Core/DataManagement/FileUploadProcessor.Venues.cs

If we've revalidated we should commit the result!

Add missing Commit()

---

src/Dfc.CourseDirectory.Core/DataManagement/FileUploadProcessor.Courses.cs
src/Dfc.CourseDirectory.Core/DataManagement/IFileUploadProcessor.cs
src/Dfc.CourseDirectory.Core/InvalidStateException.cs
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/CoursesDataManagementController.cs
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/DeleteUpload.cs
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/DeleteUpload.cshtml
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/DeleteUploadSuccess.cshtml
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Courses/DeleteUploadTests.cs

- Create delete course upload page.
- Delete success page.
- Tests

SDD-871 create course delete upload page

---

src/Dfc.CourseDirectory.WebV2/Features/ProviderDashboard/Dashboard.cshtml

- Changed Card Template on dashboard.

SDD-884 - Card Template on dashboard

---

src/Dfc.CourseDirectory.Core/DataStore/CosmosDb/Models/Course.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/UpsertCoursesFromCosmosHandler.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/CourseRunDetail/CourseRunDetail.cs
tests/Dfc.CourseDirectory.Testing/DataStore/CosmosDb/Queries/CreateCourse.cs
tests/Dfc.CourseDirectory.Testing/DataStore/CosmosDb/QueryHandlers/CreateCourseHandler.cs
tests/Dfc.CourseDirectory.Testing/TestData/TestData.CreateCourse.cs

Also made AttendancePattern and StudyMode nullable since they're only
valid for work-based courses.

Fix TestData.CreateCourse to handle regions correctly

---

src/Dfc.CourseDirectory.WebV2/Features/ProviderDashboard/Dashboard.cshtml

- add provider context to template link.

SDD-884 - provider context link

---

src/Dfc.CourseDirectory.Core/DataManagement/ParsedCsvCourseRow.cs

- Handle 0 enum for Attendance pattern & Study Mode.

SDD-762 - Mapping Correction

---

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/CoursesDataManagementController.cs

- Updated controller to redirect to error list if there are more errors after a delete.

SDD-920 - Redirect to error list if there are more errors

---

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Dashboard.cshtml
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/DashboardTests.cs

- Added tests to dashboard to check to see if download link is visible.
- Added links to new datamanagement page.

SDD-889-ApprenticeshipDataManagementCard & tests

---

src/Dfc.CourseDirectory.WebV2/Features/ProviderDashboard/Dashboard.cshtml
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/ProviderDashboard/DashboardTests.cs

- Added Block for data management links.
- Added Tests.

SDD-888 homescreen data management links

---

src/Dfc.CourseDirectory.Core/DataManagement/FileUploadProcessor.Courses.cs
src/Dfc.CourseDirectory.Core/DataManagement/IFileUploadProcessor.cs
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/CoursesDataManagementController.cs
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/DeleteRow.cs
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/DeleteRow.cshtml
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Courses/DeleteRowTests.cs

Need to revalidate since deleting the row may cause the UploadStatus to change. Also tweaked the implementation to more-closely align to the same method in Venues and also the Delete Course Row Group functionality.

Add revalidation to Delete Course Upload row

---

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/Upload.cshtml

- Fix download link on Course upload page.

SDD-762 - Download Link on Upload page

---

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/DeleteRow.cs
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/DeleteRow.cshtml

- Added LarsQan.
- Changed text.

SDD-920-Defects - Fixing testing issues.

---

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/CoursesDataManagementController.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Courses/DeleteRowTests.cs

- Correct URL of get/post of deleting a course run.
- Updated tests

SDD-920 - Correct GET/POST URL

---

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/DeleteRow.cshtml

SDD-920 lars code change

---

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/DeleteRowGroup.cs
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/DeleteRowGroup.cshtml
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/Errors.cs
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/Errors.cshtml
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/ResolveList.cs
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/ResolveList.cshtml
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Courses/ResolveListTests.cs

Also added more tests to cover the various description, delivery and details resolve & delete links.

Don't render error rows that don't have any errors

---

src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/CreateVenue.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/CreateVenueHandler.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/UpsertCoursesFromCosmosHandler.cs
src/Dfc.CourseDirectory.Database/Pttcd/Tables/Apprenticeships.sql
src/Dfc.CourseDirectory.Database/Pttcd/Tables/Courses.sql
src/Dfc.CourseDirectory.Database/Pttcd/Tables/Venues.sql
src/Dfc.CourseDirectory.Functions/AddMissingProviderIdForeignKeys.cs
src/Dfc.CourseDirectory.WebV2/Features/Venues/AddVenue/CheckAndPublish.cs
tests/Dfc.CourseDirectory.Core.Tests/SqlDataSyncTests.cs
tests/Dfc.CourseDirectory.Testing/TestData/TestData.CreateVenue.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/Venues/AddVenue/CheckAndPublishTests.cs

Also added a function to backfill the column - AddMissingProviderIdForeignKeys.

Add ProviderId FK to Courses and Venues tables

---

src/Dfc.CourseDirectory.WebV2/Features/Home/Privacy.cshtml

- Update privacy statement link.

SDD-969 - Privacy Statement Link

---

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Apprenticeships/ApprenticeshipsDataManagementController.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Apprenticeships/UploadTests.cs

- Fix restriction on controller to be Apprenticeship provider and not FE provider.
- Fix tests to create Apprenticeship Provider in tests.

SDD-889 - Corrected restriction on controller

---

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/CheckAndPublish.cs
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/CheckAndPublish.cshtml

- Changed Course name to course.
- Correct page title that mentioned Venue.
- Added LearnAimRefTitle to table.

SDD-1002 - UI chanages to course publish

---

src/Dfc.CourseDirectory.WebV2/Features/Venues/DeleteVenue/DeleteVenue.cshtml
src/Dfc.CourseDirectory.WebV2/Features/Venues/DeleteVenue/VenueDeleted.cshtml
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/Venues/DeleteVenue/DeleteVenueTests.cs

- Updated Location to Venue on the delete journey.
- Updated test that verifies title is correct.

SDD-968-ChangeLocationToVenue

---

src/Dfc.CourseDirectory.Web/Controllers/AddCourseController.cs
src/Dfc.CourseDirectory.Web/Controllers/CoursesController.cs
src/Dfc.CourseDirectory.Web/Views/AddCourse/Summary.cshtml
src/Dfc.CourseDirectory.Web/Views/CourseSummary/Index.cshtml

- Change addcourse/summary text **Who is the course for** to **Who this course is for**

SDD-848 - Change text Who is the course for to Who this course is for

---

src/Dfc.CourseDirectory.Web/appsettings.Environment.Development.json
src/Dfc.CourseDirectory.Web/appsettings.Environment.SIT.json
src/Dfc.CourseDirectory.Web/appsettings.Environment.SIT2.json

- added ApprenticeshipsDataManagement to dev/sit/sit2

SDD-889 - Added Feature flag for ApprenticeshipsDataManagement for SIT/SIT2 & DEV

---

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Apprenticeships/Formatting.cshtml

- Added new content for formatting page.

SDD-890 - Added apprenticeship guidance page

---

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Apprenticeships/ApprenticeshipsDataManagementController.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Apprenticeships/TemplateTests.cs

- Added an action to download csv template for apprenticeships.
- Added test to confirm csv file is downloadable.

SDD-859 - Download Apprenticeships template

---

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Apprenticeships/Formatting.cshtml

- Updated apprenticeship guidance page to have a link to regions.

SDD-890 - added link to regions page

---

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Apprenticeships/Formatting.cshtml

- Changed Anchor to point to VENUERE.

SDD-890 - Fixed Venue Reference Anchor for apprenticeship formatting page

---

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Apprenticeships/ApprenticeshipsDataManagementController.cs
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Dashboard.cshtml
src/Dfc.CourseDirectory.WebV2/Features/ProviderDashboard/Dashboard.cshtml

- Added apprenticeship download stub action.
- Added asp-all-route-data="@ProviderContext.RouteValues"

SDD-889 - added stub action for apprenticeship download

---

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Venues/CheckAndPublish.cshtml

- Give venue count(s) a little more space
- Added new content under venues linked to live courses.

SDD-941 - Publish Venue Content Change

---

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Apprenticeships/Formatting.cshtml

- added asp-all-route-data="@ProviderContext.RouteValues"

SDD-890 Venues Link for admin

---

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Apprenticeships/Upload.cs
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Apprenticeships/Upload.cshtml

- Stop rendering download link when there are no apprenticeships in Pttcd.

SDD-985 - Do not display download your apprenticeships when the provider has no apprenticeships in Pttcd

---

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Apprenticeships/DeleteUpload.cshtml

- Remove unpublished from title.

SDD-866 - Remove unpublished from apprenticeship title

---

src/Dfc.CourseDirectory.Core/DataManagement/FileUploadProcessor.Venues.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/GetProviderOfferingsLastUpdated.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/GetProviderOfferingsLastUpdatedHandler.cs

Simplify query that checks the last updated offering for a provider

---

src/Dfc.CourseDirectory.Core/Content.Designer.cs
src/Dfc.CourseDirectory.Core/Content.resx
src/Dfc.CourseDirectory.Core/DataManagement/FileUploadProcessor.Apprenticeships.cs
src/Dfc.CourseDirectory.Core/Validation/ApprenticeshipValidation/RuleBuilderExtensions.cs
src/Dfc.CourseDirectory.Core/Validation/ErrorRegistry.cs
tests/Dfc.CourseDirectory.Core.Tests/DataManagementTests/ApprenticeshipUploadRowValidatorTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/NewApprenticeshipProvider/ApprenticeshipDetailsTests.cs

- Added resx error messages for apprenticeships errors

SDD-866 - added resx error messages for apprenticeships

---

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Dashboard.cshtml
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Venues/Dashboard.cs
src/Dfc.CourseDirectory.WebV2/Features/ProviderDashboard/Dashboard.cs
src/Dfc.CourseDirectory.WebV2/Features/ProviderDashboard/Dashboard.cshtml
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/DashboardTests.cs

- Added upload in progress check to the dashboard for apprenticeships.
- Added test to prove in progress link renders when uploads are in progress.

SDD-932 - Upload in progress links for apprenticeship

---

src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/GetProviderDashboardCounts.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/GetProviderDashboardCountsHandler.cs
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Dashboard.cshtml
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Venues/Dashboard.cs
src/Dfc.CourseDirectory.WebV2/Features/ProviderDashboard/Dashboard.cs
src/Dfc.CourseDirectory.WebV2/Features/ProviderDashboard/Dashboard.cshtml
tests/Dfc.CourseDirectory.Testing/TestData/TestData.CreateApprenticeshipUpload.cs
tests/Dfc.CourseDirectory.Testing/TestData/TestData.CreateStandard.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Apprenticeships/DeleteUploadTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Apprenticeships/ErrorsTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Apprenticeships/InProgressTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/DashboardTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/ProviderDashboard/DashboardTests.cs

Also fixed up TestData.CreateApprenticeshipUpload to ensure it's always
using a valid standard for each row it creates.

SDD-862 Add dashboard published/in-progress apprenticeship upload links

---

src/Dfc.CourseDirectory.Core/DataManagement/FileUploadProcessor.Apprenticeships.cs
src/Dfc.CourseDirectory.Core/DataManagement/IFileUploadProcessor.cs
src/Dfc.CourseDirectory.Core/DataManagement/Schemas/CsvApprenticeshipRowWithErrors.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/UpsertApprenticeshipUploadRowsHandler.cs
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Apprenticeships/ApprenticeshipsDataManagementController.cs
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Apprenticeships/DownloadErrors.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Apprenticeships/DownloadErrorsTests.cs

- Added download errors functionality.
- Added **basic** tests

SDD-853 - apprenticeship upload errors download

---

src/Dfc.CourseDirectory.Core/Content.Designer.cs
src/Dfc.CourseDirectory.Core/Content.resx
src/Dfc.CourseDirectory.Core/DataManagement/Errors.cs
src/Dfc.CourseDirectory.Core/Validation/ApprenticeshipValidation/Constants.cs
src/Dfc.CourseDirectory.Core/Validation/ApprenticeshipValidation/RuleBuilderExtensions.cs
src/Dfc.CourseDirectory.Core/Validation/ErrorRegistry.cs
tests/Dfc.CourseDirectory.Core.Tests/DataManagementTests/ApprenticeshipUploadRowValidatorTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/NewApprenticeshipProvider/ApprenticeshipDetailsTests.cs

- Updated apprenticeship error messages
- Updated some tests
- Added Radius range validation & its corresponding test.

SDD-868 - Apprenticeship error messages update

---

src/Dfc.CourseDirectory.Core/Validation/ApprenticeshipValidation/RuleBuilderExtensions.cs

- Include ClassroomBased & ClassroomBasedAndEmployerBased for radius check validation rule.

SDD-876 - Classroombased apprenticeship radius fix.

---

src/Dfc.CourseDirectory.WebV2/Features/Error/ErrorController.cs
src/Dfc.CourseDirectory.WebV2/Features/Error/WAFError.cshtml

- Added WAF friendly error page.

SDD-916 - Friendly WAF Error Message

---

.github/CODEOWNERS

- Removed users from codeowners file that have left.

SDD-000 - Removed users from codeowners file

---

src/Dfc.CourseDirectory.Web/Views/Apprenticeships/WhatWouldYouLikeToDo/Index.cshtml

- Changed from a link to a button.

SDD-984 - Changed from link to button

---

src/Dfc.CourseDirectory.Core/DataManagement/FileUploadProcessor.Apprenticeships.cs
src/Dfc.CourseDirectory.Core/DataManagement/FileUploadProcessor.Courses.cs
src/Dfc.CourseDirectory.Core/DataManagement/FileUploadProcessor.Venues.cs
src/Dfc.CourseDirectory.Core/DataManagement/FileUploadProcessor.cs
src/Dfc.CourseDirectory.Core/Dfc.CourseDirectory.Core.csproj
src/Dfc.CourseDirectory.Core/ReferenceData/Lars/LarsDataImporter.cs
src/Dfc.CourseDirectory.Core/Validation/VenueValidation/RuleBuilderExtensions.cs
src/Dfc.CourseDirectory.Services/Dfc.CourseDirectory.Services.csproj
src/Dfc.CourseDirectory.Web/Dfc.CourseDirectory.Web.csproj
src/Dfc.CourseDirectory.WebV2/Dfc.CourseDirectory.WebV2.csproj
src/Dfc.CourseDirectory.WebV2/Features/Venues/AddVenue/Details.cs
src/Dfc.CourseDirectory.WebV2/Features/Venues/EditVenue/Name.cs
src/Dfc.CourseDirectory.WebV2/Features/Venues/EditVenue/PhoneNumber.cs
src/Dfc.CourseDirectory.WebV2/Features/Venues/EditVenue/ProviderVenueRef.cs
src/Dfc.CourseDirectory.WebV2/Features/Venues/EditVenue/Website.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Apprenticeships/DownloadErrorsTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Apprenticeships/DownloadTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Apprenticeships/TemplateTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Courses/DownloadErrorsTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Courses/DownloadTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Courses/TemplateTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Venues/DownloadErrorsTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Venues/DownloadTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Venues/TemplateTests.cs

- This is a clone of https://github.com/SkillsFundingAgency/dfc-coursedirectory/pull/2249 - As there were lots of merge conflicts because files have moved & been removed in main.
- Whitespace trimming on Non Quoted strings

SDD-965 - Whitespace trimming

---

CourseDirectory.All.sln
Dfc.CourseDirectory.Api/Dfc.CourseDirectory.Api.sln
Dfc.CourseDirectory.Api/Resources/ArmTemplates/parameters.json
Dfc.CourseDirectory.Api/Resources/ArmTemplates/template.json
Dfc.CourseDirectory.Api/Resources/ArmTemplates/test-parameters.json
Dfc.CourseDirectory.Api/Resources/AzureDevops/GitVersion.yml
Dfc.CourseDirectory.Api/Resources/AzureDevops/azure-pipelines.yml
Dfc.CourseDirectory.Api/Resources/AzureSearch/SearchDatasource.json
Dfc.CourseDirectory.Api/Resources/AzureSearch/SearchIndex.json
Dfc.CourseDirectory.Api/Resources/AzureSearch/SearchIndexer.json
src/Dfc.CourseDirectory.Api/Dfc.CourseDirectory.Api.csproj
src/Dfc.CourseDirectory.Api/Program.cs
src/Dfc.CourseDirectory.Api/Properties/launchSettings.json
src/Dfc.CourseDirectory.Api/Startup.cs
src/Dfc.CourseDirectory.Api/appsettings.Development.json
src/Dfc.CourseDirectory.Api/appsettings.Environment.Development.json
src/Dfc.CourseDirectory.Api/appsettings.Environment.PreProduction.json
src/Dfc.CourseDirectory.Api/appsettings.Environment.Production.json
src/Dfc.CourseDirectory.Api/appsettings.Environment.SIT.json
src/Dfc.CourseDirectory.Api/appsettings.Environment.SIT2.json
src/Dfc.CourseDirectory.Api/appsettings.Testing.json
src/Dfc.CourseDirectory.Api/appsettings.json
tests/Dfc.CourseDirectory.Api.Tests/Dfc.CourseDirectory.Api.Tests.csproj

Merge of the new empty Open API project directory structure into main

[SDD-1126] Initial commit of the Course Directory Public API

---

src/Dfc.CourseDirectory.WebV2/Features/ProviderDashboard/Dashboard.cshtml

- Removed Data management banner as this is now live.

SDD-1059 - Removed data upload banner

---

src/Dfc.CourseDirectory.Core/Configuration/LarsSearchSettings.cs
src/Dfc.CourseDirectory.Core/FeatureFlags.cs
src/Dfc.CourseDirectory.Core/Search/Models/Lars.cs
src/Dfc.CourseDirectory.Web/Controllers/LarsSearchController.cs
src/Dfc.CourseDirectory.Web/Controllers/QualificationsController.cs
src/Dfc.CourseDirectory.Web/Controllers/RegulatedQualificationController.cs
src/Dfc.CourseDirectory.Web/Controllers/UnregulatedCoursesController.cs
src/Dfc.CourseDirectory.Web/Startup.cs
src/Dfc.CourseDirectory.Web/ViewComponents/LarsSearchResult/LarsSearchResultItemModel.cs
src/Dfc.CourseDirectory.Web/appsettings.Development.json
src/Dfc.CourseDirectory.Web/appsettings.Environment.Development.json
src/Dfc.CourseDirectory.Web/appsettings.Environment.PreProduction.json
src/Dfc.CourseDirectory.Web/appsettings.Environment.Production.json
src/Dfc.CourseDirectory.Web/appsettings.Environment.SIT.json
src/Dfc.CourseDirectory.Web/appsettings.Environment.SIT2.json
src/Dfc.CourseDirectory.Web/appsettings.json
src/Dfc.CourseDirectory.WebV2/Content/components/search-input.css
src/Dfc.CourseDirectory.WebV2/Content/pages/choosequalification/choosequalifcation.css
src/Dfc.CourseDirectory.WebV2/Features/ChooseQualification/ChooseQualification.cs
src/Dfc.CourseDirectory.WebV2/Features/ChooseQualification/ChooseQualification.cshtml
src/Dfc.CourseDirectory.WebV2/Features/ChooseQualification/ChooseQualificationController.cs
tests/Dfc.CourseDirectory.WebV2.Tests/CourseDirectoryApplicationFactory.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/ChooseQualification/ChooseQualificationTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/MvcTestBase.cs
tests/Dfc.CourseDirectory.WebV2.Tests/Startup.cs

Add course journey moved to v2.

SDD-1064 - course add journey list page

---

src/Dfc.CourseDirectory.Web/Controllers/RegulatedQualificationController.cs
src/Dfc.CourseDirectory.WebV2/Features/ChooseQualification/ChooseQualification.cshtml
src/Dfc.CourseDirectory.WebV2/Features/ProviderDashboard/Dashboard.cshtml

- Fix to remove require provider context from controller.

SDD-1064 - provider context fix

---

src/Dfc.CourseDirectory.Core/Models/SelectCourse.cs
src/Dfc.CourseDirectory.Web/Controllers/CoursesController.cs
src/Dfc.CourseDirectory.Web/Controllers/RegulatedQualificationController.cs
src/Dfc.CourseDirectory.WebV2/Features/ChooseQualification/CheckAndPublish.cshtml
src/Dfc.CourseDirectory.WebV2/Features/ChooseQualification/ChooseQualification.cs
src/Dfc.CourseDirectory.WebV2/Features/ChooseQualification/ChooseQualification.cshtml
src/Dfc.CourseDirectory.WebV2/Features/ChooseQualification/ChooseQualificationController.cs
src/Dfc.CourseDirectory.WebV2/Features/ChooseQualification/CourseDescription.cs
src/Dfc.CourseDirectory.WebV2/Features/ChooseQualification/CourseDescription.cshtml
src/Dfc.CourseDirectory.WebV2/Features/ChooseQualification/CourseRun.cs
src/Dfc.CourseDirectory.WebV2/Features/ChooseQualification/CourseRun.cshtml
src/Dfc.CourseDirectory.WebV2/Features/ChooseQualification/CourseSelected.cs
src/Dfc.CourseDirectory.WebV2/Features/ChooseQualification/DeliveryMethod.cshtml
src/Dfc.CourseDirectory.WebV2/Features/ChooseQualification/DeliveryMode.cs
src/Dfc.CourseDirectory.WebV2/Features/ChooseQualification/FlowModel.cs
src/Dfc.CourseDirectory.WebV2/Features/ChooseQualification/SelectDeliveryMode.cshtml
src/Dfc.CourseDirectory.WebV2/Features/ProviderDashboard/Dashboard.cshtml
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/ChooseQualification/ChooseQualificationTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/ChooseQualification/CourseDescriptionTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/ChooseQualification/CourseRunTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/ChooseQualification/SelectDeliveryModeTests.cs

- Course Description page & tests.
- Deliver Mode Page & tests
- Course Run Page & tests

SDD-1066 - Course Description Page

---

src/Dfc.CourseDirectory.WebV2/Features/HelpdeskDashboard/Dashboard.cshtml
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/HelpdeskDashboard/DashboardTests.cs

- Update dashboard to reference open data reports.
- Change dashboard to have a new layout
- added two new tests.

SDD-1014 - Updated Dashboard Layout

---

src/Dfc.CourseDirectory.Core/Models/SelectCourse.cs
src/Dfc.CourseDirectory.WebV2/Features/ChooseQualification/ChooseQualification.cshtml
src/Dfc.CourseDirectory.WebV2/Features/ChooseQualification/ChooseQualificationController.cs
src/Dfc.CourseDirectory.WebV2/Features/ChooseQualification/CourseRun.cs
src/Dfc.CourseDirectory.WebV2/Features/ChooseQualification/CourseSelected.cs
src/Dfc.CourseDirectory.WebV2/Features/ChooseQualification/FlowModel.cs

SDD-1042 - CourseName bug

---

src/Dfc.CourseDirectory.WebV2/Features/Providers/Reporting/ProviderTypeReport.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/Providers/Reporting/ProviderTypeReportTests.cs

Simplifies the "Provider Type Report" output.

Merge Feature/SDD-1108 into Main

---

src/Dfc.CourseDirectory.Core/ReferenceData/Onspd/OnspdDataImporter.cs

updating from feb 2021 to aug 2022

Adds NCSLT-1226 to Hotfix 11

---

src/Dfc.CourseDirectory.Core/ReferenceData/Onspd/OnspdDataImporter.cs

updating from feb 2021 to aug 2022

Updating the ONSPD filename

---

src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/OpenData/GetLiveCoursesWithRegionsAndVenuesReport.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/OpenData/GetLiveCourseRunsWithRegionsAndVenuesReportHandler.cs
src/Dfc.CourseDirectory.WebV2/Features/OpenData/Reporting/LiveCourseWithRegionsAndVenuesReport.cs

Adds NCSLT-1385 to Sprint 24 release branch

---

src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/OpenData/GetLiveCoursesWithRegionsAndVenuesReport.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/OpenData/GetLiveCourseRunsWithRegionsAndVenuesReportHandler.cs
src/Dfc.CourseDirectory.WebV2/Features/OpenData/Reporting/LiveCourseWithRegionsAndVenuesReport.cs

Reverts SkillsFundingAgency/dfc-coursedirectory#2351

Revert "Adds NCSLT-1385 to Sprint 24 release branch" (change is not required)

---

src/Dfc.CourseDirectory.FindACourseApi/Features/TLevels/TLevels.cs

Substituted venue details with provider details if provided.

NCSLT-4609 T Level Courses - Resolve the issue with missing Venue details

---

src/Dfc.CourseDirectory.FindACourseApi/Features/TLevels/TLevels.cs

* added substitute contact details
* Fixed type inference
* made substitute contact details nullable
* removed substitute contact details for venue
* changed substitute contact details to venue
* added empty string check to substitute contact details
* reverted substitute website empty check
* added null checks

Merge Release 29 to Main now live

---

src/Dfc.CourseDirectory.Core/SqlDataSync.cs
utils/Cosmos/Dfc.CosmosBulkUtils/Config/PatchConfig.cs
utils/Cosmos/Dfc.CosmosBulkUtils/Dfc.CosmosBulkUtils.csproj
utils/Cosmos/Dfc.CosmosBulkUtils/Properties/launchSettings.json
utils/Cosmos/Dfc.CosmosBulkUtils/Services/FileService.cs
utils/Cosmos/Dfc.CosmosBulkUtils/patch-config-example.json
utils/Cosmos/Dfc.CosmosBulkUtils/patch-provider-types-2-to-0.json
utils/Cosmos/Dfc.CosmosBulkUtils/patch-provider-types-3-to-1.json
utils/Cosmos/Dfc.CosmosBulkUtils/patch-provider-types-6-to-4.json
utils/Cosmos/Dfc.CosmosBulkUtils/patch-provider-types-7-to-5.json

Contains fixes that allow the Utility tool to run

Ncslt 5516

---

src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/OpenData/GetLiveCoursesWithRegionsAndVenuesReport.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/OpenData/GetLiveCourseRunsWithRegionsAndVenuesReportHandler.cs
src/Dfc.CourseDirectory.WebV2/Features/Courses/Reporting/AllCoursesReport.cs

Release/live service/49

---

src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/GetSectorsAttachedWithCourses.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/GetSectorsAttachedWithCoursesHandler.cs
src/Dfc.CourseDirectory.FindACourseApi/Features/Sectors/Sectors.cs
tests/Dfc.CourseDirectory.FindACourseApi.Tests/FeatureTests/SectorsTests.cs

Merging new changes for 174755

Aac fac changes

---

.github/CODEOWNERS
Dfc.CourseDirectory.Api/Resources/ArmTemplates/parameters.json
Dfc.CourseDirectory.Api/Resources/ArmTemplates/template.json
Dfc.CourseDirectory.Api/Resources/ArmTemplates/test-parameters.json
Dfc.CourseDirectory.FindACourseApi/Resources/ArmTemplates/parameters.json
Dfc.CourseDirectory.FindACourseApi/Resources/ArmTemplates/template.json
Dfc.CourseDirectory.FindACourseApi/Resources/ArmTemplates/test-parameters.json
Dfc.CourseDirectory/Resources/ArmTemplates/parameters.json
Dfc.CourseDirectory/Resources/ArmTemplates/template.json
Dfc.CourseDirectory/Resources/ArmTemplates/test-parameters.json

Add conditional suffix for PP and PRD migrated

---

src/Dfc.CourseDirectory.Core/DataStore/Sql/Queries/DeleteArchivedCourses.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/DeleteArchivedCoursesHandler.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/PublishCourseUploadHandler.cs
src/Dfc.CourseDirectory.Database/Dfc.CourseDirectory.Database.sqlproj
src/Dfc.CourseDirectory.Database/Pttcd/Indexes/IX_CourseRuns_CourseRunStatus_UpdatedOn.sql
src/Dfc.CourseDirectory.Database/Pttcd/Indexes/IX_Courses_CourseStatus_UpdatedOn.sql
src/Dfc.CourseDirectory.Database/Pttcd/Indexes/IX_FindACourseIndex_Live_LastSynced.sql
src/Dfc.CourseDirectory.Database/Pttcd/StoredProcedures/RemoveRedundantRecords.sql
src/Dfc.CourseDirectory.Database/Scripts/Script.PostDeploy.sql
src/Dfc.CourseDirectory.Functions/DeleteArchivedCourses.cs

Create Azure function in Course Directory to remove archive records

Create Azure function in Course Directory to remove archive records

---

src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/OpenData/GetLiveCourseRunsWithRegionsAndVenuesReportHandler.cs
src/Dfc.CourseDirectory.WebV2/Features/Courses/Reporting/AllCoursesReport.cs
src/Dfc.CourseDirectory.WebV2/Features/OpenData/Reporting/LiveCourseWithRegionsAndVenuesReport.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/DataManagement/Courses/Reporting/AllCoursesReportTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/OpenData/Reporting/LiveCourseProviderReportTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/FeatureTests/OpenData/Reporting/LiveCourseWithRegionsAndVenuesReportTests.cs

Rename column COURSE_DESCRIPTION to WHO_THIS_COURSE_IS_FOR in reports

Rename column COURSE_DESCRIPTION to WHO_THIS_COURSE_IS_FOR in reports

---

src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/GetLatestUnpublishedCourseUploadForProviderHandler.cs

Fixed the issue with unpublishing courses for a provider.

Bug fix 185365

---

src/Dfc.CourseDirectory.Core/DataManagement/FileUploadProcessor.Courses.cs
src/Dfc.CourseDirectory.Core/DataManagement/FileUploadProcessor.Venues.cs
src/Dfc.CourseDirectory.Core/DataManagement/Schemas/CsvNonLarsCourseRow.cs
src/Dfc.CourseDirectory.Core/DataManagement/Schemas/CsvVenueRow.cs
src/Dfc.CourseDirectory.Core/Dfc.CourseDirectory.Core.csproj
src/Dfc.CourseDirectory.Core/Validation/CourseValidation/RuleBuilderExtensions.cs
src/Dfc.CourseDirectory.Core/Validation/RuleBuilderExtensions.cs
src/Dfc.CourseDirectory.Core/Validation/Rules.cs
src/Dfc.CourseDirectory.Core/Validation/TLevelValidation/RuleBuilderExtensions.cs
src/Dfc.CourseDirectory.Core/Validation/VenueValidation/RuleBuilderExtensions.cs
src/Dfc.CourseDirectory.Services/Dfc.CourseDirectory.Services.csproj
tests/Dfc.CourseDirectory.Core.Tests/DataManagementTests/FileUploadProcessorTests.Venues.cs
tests/Dfc.CourseDirectory.Core.Tests/Dfc.CourseDirectory.Core.Tests.csproj
tests/Dfc.CourseDirectory.Core.Tests/ModelTests/PostcodeTests.cs
tests/Dfc.CourseDirectory.Testing/DatabaseFixture.cs
tests/Dfc.CourseDirectory.Testing/Dfc.CourseDirectory.Testing.csproj

Dot Net8 Upgrade for dfc-coursedirectory repo batch 1

Dot Net8 Upgrade for dfc-coursedirectory repo batch 1

---

src/Dfc.CourseDirectory.Core/Validation/CourseValidation/RuleBuilderExtensions.cs
src/Dfc.CourseDirectory.Web/Controllers/CopyCourse/CopyCourseRunController.cs
src/Dfc.CourseDirectory.Web/Controllers/EditCourse/EditCourseController.cs
src/Dfc.CourseDirectory.Web/Controllers/EditCourse/EditCourseRunController.cs
src/Dfc.CourseDirectory.Web/Validation/CopyCourseRunSaveViewModelValidator.cs
src/Dfc.CourseDirectory.Web/Validation/EditCourseRunSaveViewModelValidator.cs
src/Dfc.CourseDirectory.Web/Validation/EditCourseSaveViewModelValidator.cs
src/Dfc.CourseDirectory.Web/ViewModels/CopyCourse/CopyCourseRunSaveViewModel.cs
src/Dfc.CourseDirectory.Web/ViewModels/EditCourse/EditCourseRunSaveViewModel.cs
src/Dfc.CourseDirectory.WebV2/Security/ClaimsPrincipalCurrentUserProvider.cs
tests/Dfc.CourseDirectory.Web.Tests/Validation/CopyCourseRunSaveViewModelValidatorTests.cs
tests/Dfc.CourseDirectory.Web.Tests/Validation/EditCourseRunSaveViewModelValidatorTests.cs

.NET8 upgrade for batch 3 of dfc-coursedirectory repo. This batch includes following projects:
- Dfc.CourseDirectory.Web
- Dfc.CourseDirectory.Web.Tests

.Net8 Upgrade for batch 3 of dfc-coursedirectory repo.

---

src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/Formatting.cshtml
src/Dfc.CourseDirectory.WebV2/Features/DataManagement/Courses/NonLarsFormatting.cshtml

Fix delivery mode incorrect description in 'Course file format requirements' page.

Fix delivery mode incorrect description in 'Course file format requirements' page.

---

src/Dfc.CourseDirectory.WebV2/Features/DeleteCourseRun/DeleteCourseRun.cs
src/Dfc.CourseDirectory.WebV2/Features/DeleteCourseRun/DeleteCourseRunController.cs

Reverts SkillsFundingAgency/dfc-coursedirectory#2636

Revert "Bug fix to show links when non lars course deleted"

---

src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/DeleteTLevelHandler.cs

[Sprint ticket- AD-169133](https://sfa-gov-uk.visualstudio.com/National%20Careers%20Service%20(NCS)/_workitems/edit/169133)

Merge Ad-169133 into the release branch

---

.gitignore
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/CreateProviderFromUkrlpDataHandler.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/GetProvidersHandler.cs
src/Dfc.CourseDirectory.Core/DataStore/Sql/QueryHandlers/UpdateProviderFromUkrlpDataHandler.cs
src/Dfc.CourseDirectory.Core/ReferenceData/Ukrlp/UkrlpSyncHelper.cs
src/Dfc.CourseDirectory.Functions/Dfc.CourseDirectory.Functions.csproj
src/Dfc.CourseDirectory.Functions/SyncUkrlp.cs
src/Dfc.CourseDirectory.WebV2/SharedViews/Components/ProviderInfoPanel.cshtml
src/Dfc.CourseDirectory.WebV2/UrlUtil.cs
tests/Dfc.CourseDirectory.Core.Tests/ReferenceDataTests/UkrlpSyncHelperTests.cs
tests/Dfc.CourseDirectory.WebV2.Tests/ViewComponentTests/ProviderInfoPanelTests.cs

**ADO ticket**: https://dev.azure.com/sfa-gov-uk/National%20Careers%20Service%20(NCS)/_workitems/edit/237606
**Service NOW incident**: https://dfe.service-now.com/now/nav/ui/classic/params/target/incident.do%3Fsys_id%3Da1c824ba3b9a26905408ae8a04e45aa1%26sysparm_stack%3D%26sysparm_view%3D
**Changes made**:
| File name(s) | Change made |
| ---- | ---- |
| UpdateProviderFromUkrlpDataHandler.cs | Update to logs, linting and formatting |
| UkrlpSyncHelper.cs | Update to logs, linting and formatting, renaming variables, adding usage of `Commit()` to save the result of the transaction (after all processing is complete) |
| Dfc.CourseDirectory.Functions.csproj | Addition of new NuGet package - `Newtonsoft.Json` |
| SyncUkrlp.cs | Functions renamed and logs enhanced, `SyncProviderByUkprn` function …

[AD-237606] INC01639235 - contact details not updating in PttCD

---

src/Dfc.CourseDirectory.Core/ReferenceData/Ukrlp/UkrlpSyncHelper.cs
tests/Dfc.CourseDirectory.Core.Tests/ReferenceDataTests/UkrlpSyncHelperTests.cs

This reverts commit https://github.com/SkillsFundingAgency/dfc-coursedirectory/commit/df9b0fd3f8f6b326bad8014ec15cc1bbdb7b1e84.

Revert "updated unit tests to use another dispatcher"
